var FILMS = [
"Auguste and Louis Lumière, Fr:",
"L'Arrivée d'un train en gare de la Ciotat (1895)",
"La Sortie de l'usine Lumière à Lyon (1895)",
"L'Arroseur arrosé (1895)",
"Le Repas de bébé (1895)",
"Georges Meliès, Fr:",
"Escamotage d'une Dame chez Robert-Houdini (1896)",
"Le Voyage dans la lune (1902)",
"Le Royaume des fées (1903)",
"La Lanterne magique (1903)",
"Le Voyage à travers l'impossible (1904)",
"Thomas Edison Productions, US:",
"Annabelle Serpentine Dance (1895)",
"The Kiss (1896)",
"Mr. Edison at Work in His Chemical Laboratory (1897)",
"Electrocuting an Elephant (1903)",
"The Patchwork Girl of Oz (1914)",
"Edwin S. Porter, US:",
"Terrible Teddy, the Grizzly King (1901)",
"Circular Panorama of Electric Tower (1901)",
"Pan-American Exposition by Night (1901)",
"Life of an American Fireman (1902)",
"Uncle Josh at the Moving Picture Show (1902)",
"Uncle Tom's Cabin (1903)",
"The Gay Shoe Clerk (1903)",
"Romance of the Rails (1903)",
"The Great Train Robbery (1903)",
"The Teddy Bears (1907)",
"D.W. Griffith Biograph Shorts, US:",
"The Lonely Villa (1909)",
"Corner in Wheat (1909)",
"His Trust (1911)",
"The Lonedale Operator (1911)",
"The New York Hat (1912)",
"The Musketeers of Pig Alley (1912)",
"The Battle of Elderbush Gulch (1913)",
"La Fée aux choux (Alice Guy, 1896, Fr)",
"A House Divided (Alice Guy, 1913, US)",
"Cabiria (Giovanni Pastrone, 1914, Italy)",
"Fantomas (Louis Feuillade, 1914, France)",
"The Birth of a Nation (D.W. Griffith, 1915, US)",
"Les Vampires (Louis Feuillade, 1915, Fr)",
"Intolerance (D. W. Griffith, 1916, US)",
"The Cheat (Cecil B. de Mille, 1916, US)",
"The Immigrant (Charles Chaplin, 1917, US)",
"The Outlaw and His Wife (Victor Sjöström, 1918, Sweden)",
"Broken Blossoms (D. W. Griffith, 1919, US)",
"Sunnyside (Charles Chaplin, 1919, US)",
"The Cabinet Of Dr. Caligari (Robert Wiene, 1920, Ger)",
"The Phantom Carriage (Victor Sjöström, 1920, Sweden)",
"The Blot (Lois Weber, 1921, US)",
"Nosferatu (F. W. Murnau, 1922, Ger)",
"By the Law (Lev Kuleshov, 1922, USSR)",
"Häxan: Witchcraft through the Ages (Benjamin Christensen, 1922, Denmark)",
"Foolish Wives (Erich von Stroheim, 1922, US)",
"Safety Last (Fred Newmeyer/Sam Taylor, 1923, US)",
"Kino Eye (Dziga Vertov, 1924, USSR)",
"The Last Laugh (F. W. Murnau, 1924, Ger)",
"Greed (Erich von Stroheim, 1924, US)",
"Sherlock Junior (Buster Keaton, 1924, US)",
"The Saga of Gösta Berling (Mauritz Stiller, 1924, Sweden)",
"L'Inhumaine (Marcel L'Herbier, 1924)",
"The Iron Horse (John Ford, 1924, US)",
"Battleship Potemkin (Sergei Eisenstein, 1925, USSR)",
"The Gold Rush (Charles Chaplin, 1925, US)",
"Body and Soul (Oscar Micheaux, 1925, US)",
"The Joyless Street (G. W. Pabst, 1925, Ger)",
"The General (Buster Keaton, 1926, US)",
"The Lodger (Alfred Hitchcock, 1926, GB)",
"Mother (V. I. Pudovkin, 1926, USSR)",
"Page Of Madness (Teinosuke Kinugasa, 1926, Jap)",
"Metropolis (Fritz Lang, 1927, Ger)",
"The End of St. Petersburg (V. I. Pudovkin, 1927, USSR)",
"Napoleon (Abel Gance, 1927, Fr)",
"Sunrise (F. W. Murnau, 1927, US)",
"The Jazz Singer (Alan Crosland, 1927, US)",
"October (Sergei Eisenstein, 1928, USSR)",
"L'Argent (Marcel L'Herbier, 1928, Fr)",
"The Crowd (King Vidor, 1928, US)",
"Storm over Asia (Vsevolod Pudovkin, 1928, USSR)",
"Passion de Jeanne d'Arc (Carl Th. Dreyer, 1928, Fr)",
"Sous les Toits de Paris (René Clair, 1929, Fr)",
"Earth (Alexander Dovzhenko, 1930, USSR)",
"The Blue Angel (Josef von Sternberg, 1930, Ger)",
"L'Age d'Or (Luis Buñuel, 1930, Fr)",
"Borderline (Kenneth MacPherson, 1930, GB) M (Fritz Lang, 1931, Germany)",
"The Exile (Oscar Michaux, 1931, US)",
"I Am a Fugitive from a Chain Gang (Mervyn LeRoy, 1932, US)",
"Zéro de Conduite (Jean Vigo, 1933, Fr)",
"Christopher Strong (Dorothy Arzner, 1933, US)",
"El Compadre Mendoza (Fernando de Fuentes, 1933, Mexico)",
"L'Atalante (Jean Vigo, 1934, Fr)",
"Le Crime du M. Lange (Jean Renoir, 1935, Fr)",
"The 39 Steps (Alfred Hitchcock, 1935, GB)",
"Modern Times (Charles Chaplin, 1935, US)",
"Sisters of the Gion (Kenji Mizoguchi, 1936, Jap)",
"La Grande Illusion (Jean Renoir, 1937, Fr)",
"Alexander Nevsky (Sergei Eisenstein, 1938, USSR)",
"Le Jour se lève (Marcel Carné, 1939, Fr)",
"Mr. Smith Goes to Washington (Frank Capra, 1939, US)",
"La Règle du jeu (Jean Renoir, 1939, Fr)",
"Thief of Bagdad (Michael Powell, 1940, GB)",
"Jew Süss (Veit Harlan, 1940, Ger)",
"Citizen Kane (Orson Welles, 1941, US)",
"Day Of Wrath (Carl Th. Dreyer, 1943, Denmark)",
"Le Corbeau (Henri-Georges Clouzot, 1943, Fr)",
"Ivan the Terrible, Part I (Sergei Eisenstein, 1944, USSR)",
"Les Enfants du Paradis (Marcel Carné, 1945, Fr)",
"Open City (Roberto Rossellini, 1945, It)",
"Brief Encounter (David Lean, 1945, GB)",
"Paisan (Roberto Rossellini, 1946, It)",
"The Murderers Are Among Us (Wolfgang Staudte, 1946, Ger)",
"La Terra Trema (LuchinoVisconti, 1948, It)",
"The Red Shoes (Michael Powell/Emeric Pressburger, 1948, GB)",
"Bicycle Thieves (Vittorio De Sica, 1948, It)",
"Diary of A Country Priest (Robert Bresson, 1950, Fr)",
"The Third Man (Carol Reed, 1950, UK)",
"Los Olvidados (Luis Buñuel, 1950, Mexico)",
"Sunset Boulevard (Billy Wilder, 1950, US)",
"Rashomon (Akira Kurosawa, 1950, Jap)",
"The River (Jean Renoir, 1951, Fr/India)",
"Les Jeux interdits (René Clément, 1952, Fr)",
"Madame De (Max Ophuls, 1953, Fr)",
"Tokyo Story (Yasujiro Ozu, 1953, Jap)",
"Le Salaire de la peur (Henri-Georges Clouzot, 1953, Fr)",
"Ugetsu Monogatari (Kenji Mizoguchi, 1953, Jap)",
"Les Vacances de M. Hulot (Jacques Tati, 1953, Fr)",
"Salt of the Earth (Herbert J. Biberman, 1953, US)",
"Voyage in Italy (Roberto Rossellini, 1953, It)",
"The Little Fugitive (Ray Ashley, 1953, US)",
"Seven Samurai (Akira Kurosawa, 1954, Jap)",
"Sansho the Bailiff (Kenji Mizoguchi, 1954, Jap)",
"On the Waterfront (Elia Kazan, 1954, US)",
"Ordet (Carl Th. Dreyer, 1954, Den)",
"La Strada (Federico Fellini, 1954, It)",
"Pather Panchali (Satyajit Ray, 1955, India)",
"Bob le Flambeur (Jean-Pierre Melville, 1955, Fr)",
"Death of a Cyclist (Juan Antonio Bardem, 1955, Spain)",
"Kanal (Andrzej Wajda, 1956, Poland)",
"Le Ballon rouge (Albert Lamorisse, 1956, Fr)",
"The Burmese Harp (Kon Ichikawa, 1956, Japan)",
"Wild Strawberries (Ingmar Bergman, 1957, Sw)",
"The Cranes Are Flying (Mikhail Kalatozov, 1957, USSR)",
"Nights of Cabiria (Federico Fellini, 1957, It)",
"Ashes and Diamonds (Andrzej Wajda, 1958, Poland)",
"Vertigo (Alfred Hitchcock, 1958, US)",
"Ballad of a Soldier (Grigori Chukrai, 1959, USSR)",
"A Bout de souffle (Jean-Luc Godard, 1959, Fr)",
"Hiroshima mon Amour (Alain Resnais, 1959, Fr)",
"Les 400 Coups (Francois Truffaut, 1959, Fr)",
"Pickpocket (Robert Bresson, 1959, Fr)",
"Shadows (John Cassavetes, 1959, US)",
"The World of Apu (Satyajit Ray, 1959, India)",
"L'Avventura (Michelangelo Antonioni, 1960, It)",
"The House Maid (Kim Ki",
"-Young, 1960, South Korea)",
"Mother Joan of the Angels (Jerzy Kawalerowicz, 1960, Poland)",
"Rocco and His Brothers (Luchino Visconti, 1960, It)",
"The Hidden Star (Ritwak Ghatak, 1960, India)",
"Peeping Tom (Michael Powell, 1960, Eng)",
"Accattone (Pier Paolo Pasolini, 1961, It)",
"L'Année dernière à Marienbad (Alain Resnais, 1961, Fr)",
"The Island (Kaneto Shindo, 1961, Jap)",
"The Exiles (Kent McKenzie, 1961, US)",
"Viridiana (Luis Buñuel, 1961, Sp)",
"Cléo à 5 de 7 (Agnès Varda, 1961, Fr)",
"The Connection (Shirley Clarke, 1961, US)",
"An Autumn Afternoon (Yasujiro Ozu, 1962, Jap)",
"The Eclipse (Michelangelo Antonioni, 1962, It)",
"La Jetée (Chris Marker, 1962, Fr)",
"8 1/2 (Federico Fellini, 1963, It)",
"The Leopard (Luchino Visconti, 1963, It)",
"Vidas Secas (Nelson Pereira Dos Santos, 1963, Brazil)",
"The Red Desert (Michelangelo Antonioni, 1964, It)",
"Shadows of Our Forgotten Ancestors (Sergei Paradjanov, 1964, USSR)",
"Dr. Strangelove (Stanley Kubrick, 1964, US)",
"A Hard Day's Night (Richard Lester, 1964, GB)",
"The Gospel According to St. Matthew (Pier Paolo Pasolini, 1964, It)",
"La Noire (Ousmane Sembene, 1965, Senegal)",
"Pierrot le Fou (Jean-Luc Godard, 1965, Fr/It)",
"The Round-Up (Miklós Jancsó, 1965, Hun)",
"The Shop on Main Street (Jan Kadar/Elmar Klos, 1965, Slovakia)",
"Not Reconciled (Jean-Marie Straub and Danielle Huillet, 1965, FRG)",
"Le Bonheur (Agnès Varda, 1965, Fr)",
"The Battle of Algiers (Gillo Pontecorvo, 1966, It)",
"Les Demoiselles de Rochefort (Jacques Demy, 1966, Fr)",
"Father: Diary of One Week (Istvan Szabo, 1966, Hungary)",
"Blow-up (Antonioni, 1966, GB)",
"Daisies (Vera Chytilova, 1966, Czech)",
"The Party and the Guests (Jan Němec, 1966, Czech)",
"Loves of a Blonde (Miloš Forman, 1966, Czech)",
"Au Hasard, Balthazar (Robert Bresson, 1966, Fr/Sw)",
"Andrei Rublev (Andrei Tarkovsky, 1966, USSR)",
"Persona (Ingmar Bergman, 1966, Sw)",
"Hawks and Sparrows (Pier Paolo Pasolini, 1966, It)",
"David Holzman's Diary (Jim McBride, 1967, US)",
"2 ou 3 Choses que je sais d'elle (Jean-Luc Godard, 1967, Fr)",
"Playtime (Jacques Tati, 1967, Fr)",
"Weekend (Jean-Luc Godard, 1967, Fr)",
"Belle de Jour (Luis Buñuel, 1967, Fr)",
"War and Peace (Sergei Bondarchuk, 1967, USSR)",
"Land in Anguish (Glauber Rocha, 1967, Brazil)",
"Innocence Unprotected (Dusan Makavejev, 1968, Yugo)",
"If (Lindsay Anderson, 1968, GB)",
"Ma Nuit chez Maude (Eric Rohmer, 1968, Fr)",
"Death by Hanging (Nagisa Oshima, 1968, Jap)",
"Once Upon a Time in the West (Sergio Leone, 1968, It)",
"Petulia (Richard Lester, 1968, US)",
"Memories of Underdevelopment (Tomas Gutierrez Alea, 1968, Cuba)",
"The Conformist (Bernardo Bertolucci, 1969, It)",
"Quatre Nuits d'un reveur (Robert Bresson, 1969, Fr)",
"The Night of Counting the Years (Shadi Abdelsalam, 1969, UAR)",
"The Color of Pomegranates (Sergei Parajanov, 1969, USSR)",
"Easy Rider (Dennis Hopper, 1969, US)",
"Blood of the Condor (Jorge Sanjines, 1969, Bolivia)",
"Antonio das Mortes (Glauber Rocha, 1969, Brazil)",
"Lucia (Humberto Solas, 1969, Cuba)",
"King Lear (Grigori Kozintsev, 1970, USSR)",
"Performance (Nicolas Roeg/Donald Cammell, 1970, GB)",
"Sweet Sweetback's Badasssss Song (Melvin Van Peebles, 1971, US)",
"Mon Oncle Antoine (Claude Jutra, 1971, Can)",
"Shaft (Gordon Parks, 1971, US)",
"The Last Picture Show (Peter Bogdanovich, 1971, US)",
"W.R. Mysteries of the Organism (Dusan Makavejev, 1971, Yugo)",
"How Tasty Was My Little Frenchman (Nelson Pereira Dos Santos, 1971, Brazil)",
"Le Charme discrèt de la Bourgeoisie (Luis Buñuel, 1972, Fr)",
"Aguirre, Wrath Of God (Werner Herzog, 1972, FRG)",
"Last Tango in Paris (Bernardo Bertolucci, 1972, It/Fr)",
"The Spirit of The Beehive (Victor Erice, 1973, Sp)",
"La Nuit américaine (François Truffaut, 1973, Fr)",
"Mean Streets (Martin Scorsese, 1973, US)",
"Badlands (Terrence Malick, 1973, US)",
"La Maman et la putain (Jean Eustache, 1973, Fr)",
"India Song (Marguerite Duras, 1974, Fr)",
"Xala (Ousmane Sembene, 1974, Senegal)",
"Picnic at Hanging Rock (Peter Weir, 1975, Australia)",
"Cria Cuervos (Carlos Saura, 1975, Sp)",
"Tout va bien (Jean-Luc Godard/Jean Pierre Gorin, 1975, Fr)",
"Jeanne Dielman... (Chantal Akerman, 1975, Belgium)",
"Travelling Players (Theodoros Angelopoulos, 1975, Greece)",
"Kings of the Road (Wim Wenders, 1976, FRG)",
"Nashville (Robert Altman, 1976, US)",
"Taxi Driver (Martin Scorsese, 1976)",
"All the President's Men (Alan Pakula, 1976, US)",
"Man of Marble (Andrzej Wajda, 1976, Poland)",
"The Ascent (Larisa Shepitko, 1976, USSR)",
"In the Realm of the Senses (Nagisa Oshima, 1976, Jap)",
"Jonas qui aura 25 dans en l’an 2000 (Alain Tanner, 1976, Switz)",
"Killer of Sheep (Charles Burnet, 1977, US)",
"Suspiria (Dario Argento, 1977)",
"L'Hypothèse du tableau volé (Raúl Ruiz, 1978, Fr)",
"The Marriage of Maria Braun (Rainer Werner Fassbinder, 1978, FRG)",
"Apocalypse Now (Francis Ford Coppola, 1979, US)",
"The Patriot (Alexander Kluge, 1979, FRG)",
"Vengeance Is Mine (Shohei Imamura, 1979, Jap)",
"Raging Bull (Martin Scorsese, 1980, US)",
"The German Sisters (Margarethe von Trotta, 1981, FRG)",
"The Draftsman's Contract (Peter Greenaway, 1982, GB)",
"Boat People (Ann Hui, 1982, Hong Kong)",
"A Question of Silence (Marleen Gorris, 1982, Netherlands)",
"The Wind (Souleymane Cisse, 1982, Mali)",
"Yol (Yomaz Güney, 1982, Turkey)",
"Videodrome (David Cronenberg, 1982, Canada)",
"The Ballad Of Narayama (Shohei Imamura, 1983, Jap)",
"Fanny and Alexander (Ingmar Bergman, 1983, Sw)",
"Carmen (Carlos Saura, 1983, Sp)",
"Nostalgia (Andrei Tarkovsky, 1983, It/USSR)",
"Yellow Earth (Chen Kaige, 1984, China)",
"Illusions (Julie Dash, 1984, US)",
"Paris, Texas (Wim Wenders, 1984, US)",
"The Home and the World (Satyajit Ray, 1984, India)",
"Camila (Maria Luisa Bemberg, 1984, Argentina)",
"Ran (Akira Kurosawa, 1985, Jap)",
"Blue Velvet (David Lynch, 1986, US)",
"Caravaggio (Derek Jarman, 1986, GB)",
"Yeelen (Souleymane Cisse, 1987, Mali)",
"Red Sorghum (Zhang Yimou, 1987, China)",
"Wedding In Galilee (Michel Khleifi, 1987, Belgium/Fr)",
"Wings of Desire (Wim Wenders, 1987, FRG)",
"Salaam Bombay! (Mira Nair, 1988, India)",
"The Decalogue (Krzystof Kieslowski, 1988, Poland)",
"Woman on the Verge of a Nervous Breakdown (Pedro Almódovar, 1988, Sp)",
"Do the Right Thing (Spike Lee, 1989, US)",
"Yaaba (Idrissa Ouedraogo, 1989, Burkina Faso)",
"The Killer (John Woo, 1989, Hong Kong)",
"The Puppet Master (Hou Hsiao-Hsien, 1989, Taiwan)",
"The Match Factory Girl (Aki Kaurismaki, 1989, Finland)",
"Crimes and Misdemeanors (Woody Allen, 1989, US)",
"Looking for Langston (Isaac Julien, 1989, GB)",
"Speaking Parts (Atom Egoyan, 1989, Can)",
"sex, lies, and videtape (Steven Soderberg, 1989, US)",
"Do the Right Thing (Spike Lee, 1989, US)",
"An Angel at My Table (Jane Campion, 1990, New Zealand)",
"I Hired a Contract Killer (Aki Kaurismäki, 1990, Finland)",
"Time of the Gypsies (Emir Kusturica, 1990, Yugoslavia)",
"Tilai (Idrissa Ouedraogo, 1990, Burkina Faso)",
"Ju Dou (Zhang Yimou, 1990, China)",
"La Belle noiseuse (Jacques Rivette, 1991, Fr)",
"The Suspended Step of the Stork (Theodoros Angelopoulos, 1991, Greece)",
"Raise the Red Lantern (Zhang Yimou, 1991, China)",
"Daughters of the Dust (Julie Dash, 1992, US)",
"Quince Tree of the Sun (Victor Erice, 1992, Sp)",
"Life According to Agfa (Assi Dayan, 1992, Israel)",
"Sankofa (Haile Gerima, 1993, Burkina Faso/Ghana)",
"Caro Diario (Nanni Moretti, 1993, Italy)",
"Satantango (Bela Tarr, 1994, Hungary)",
"Chungking Express (Wong Kar Wai, 1994, Hong Kong)",
"Vive l’amour (Tsai Ming-liang, 1994, China/Taiwan)",
"Trois Coleurs (Krzysztof Kieslowski, 1994, France/Poland)",
"Dead Man (Jim Jarmusch, 1995, US)",
"Breaking the Waves (Lars von Trier, 1996, Denmark)",
"The Pillow Book (Peter Greenaway, 1996, GB)",
"The Sweet Hereafter (Atom Egoyan, 1997, Canada)",
"Taste of Cherry (Abbas Kiarostami, 1997, Iran)",
"The River (Tsai Ming-liang, 1997, Taiwan)",
"The Celebration (Thomas Vinterberg, 1998, Denmark)",
"Flowers of Shanghai (Hou Hsaio-hsien, 1998, Taiwan)",
"Run Lola Run (Tom Tykwer, 1998, FRG)",
"Beau Travail (Claire Denis, 1999, Fr)",
"Eyes Wide Shut (Stanley Kubrick, 1999, GB)",
"A One and a Two. . . (Edward Yang, 2000, Taiwan)",
"Platform (Jia Zhangke, 2000, China)",
"Amores Perros (Alejandro Gonzales Iñarritu, 2000, Mexico)",
"In the Mood for Love (Wong Kar-Wai, 2000, Hong Kong)",
"Man Without a Past (Aki Kaurismäki, 2000, Finland)",
"Songs from the Second Floor (Roy Andersson, 2000, Sweden)",
"Eloge de l'Amour (Jean-Luc Godard, 2001, Fr)",
"Talk to Her (Pedro Almodóvar, 2002, Sp)",
"City of God (Fernando Meirelles, 2002, Brazil)",
"Waiting for Happiness (Abderrahmane Sissako, 2002, Fr/Mauritania)",
"10 (Abbas Kiarostami, 2002, Iran)",
"Russian Ark (Alexander Sokurov, 2002, Russia)",
"Le Fils (Jean-Pierre and Luc Dardenne, 2002, Belgium)",
"Uzak (Nur Bilge Ceylan, 2003, Turkey)",
"The Five Obstructions (Jørgen Leth/Lars von Trier, 2003, Denmark)",
"Caché (Michael Haneke, 2004, Fr)",
"Tropical Malady (Apichatpong Weerasethakul, 2004, Thailand)",
"La Niña Santa (Lucrecia Martel, 2004, Argentina)",
"The Death of Mr. Lazarescu, Cristi Puiu, 2005, Romania)",
"Still Life (Jia Zhangke, 2006, China)",
"Colossal Youth (Pedro Costa, 2006, Portugal)",
"Pan’s Labyrinth (Guillermo del Toro, 2006, Mexico)",
"Four Months, Three Weeks, and Two Days (Cristian Mungiu, 2007, Romania)",
"United Red Army (Wakamatsu Koji, 2008, Japan)",
"The White Ribbon (Michael Haneke, 2009, FRG)",
"Carlos (Olivier Assayas, 2010, Fr)",
"A Tree of Life (Terrence Malick, 2011, US)",
"Uncle Boonmee Who Can Recall His Past Lives (Apichatpong Weerasethakul, 2011, Thailand)",
"Trouble in Paradise (Ernst Lubitsch, 1932)",
"It Happened One Night (Frank Capra, 1934)",
"A Night at the Opera (Sam Wood, 1935)",
"My Man Godfrey (Geoffrey La Cava, 1936)",
"The Awful Truth (Leo McCarey, 1937)",
"Bringing Up Baby (Howard Hawks, 1938)",
"The Philadelphia Story (George Cukor, 1940)",
"His Girl Friday (Howard Hawks, 1940)",
"Sullivan's Travels (Preston Sturges, 1941, US)",
"The Lady Eve (Preston Sturges, 1941)",
"Some Like It Hot (Billy Wilder, 1959)",
"Annie Hall (Woody Allen, 1977)",
"Ben Hur: The Tale of the Christ (Fred Niblo, 1926)",
"Cleopatra (Cecil B. de Mille, 1934)",
"The Good Earth (Sidney Franklin, 1937)",
"Gone With the Wind (Victor Fleming, 1939)",
"The Robe (Henry Koster, 1953)",
"The Ten Commandments (Cecil B. de Mille, 1956)",
"Giant (George Stevens, 1956)",
"Ben Hur (William Wyler, 1959)",
"Spartacus (Stanley Kubrick, 1960)",
"El Cid (Anthony Mann, 1961)",
"Reds (Warren Beatty, 1981)",
"Titanic (James Cameron, 1997)",
"Gladiator (Ridley Scott, 2000)",
"The Maltese Falcon (John Huston, 1941)",
"Double Indemnity (Billy Wilder, 1944)",
"Laura (Otto Preminger, 1944)",
"Phantom Lady (Robert Siodmak, 1944)",
"Detour (Edgar G. Ulmer, 1945)",
"The Big Sleep (Howard Hawks, 1946)",
"Gun Crazy (Joseph H. Lewis, 1950)",
"The Big Heat (Fritz Lang, 1953)",
"Kiss Me Deadly (Robert Aldrich, 1955)",
"Touch of Evil (Orson Welles, 1958)",
"Point Blank (John Boorman, 1967)",
"The Long Goodbye (Robert Altman, 1973)",
"Chinatown (Roman Polanski, 1974)",
"The Conversation (Francis Ford Coppola, 1974)",
"Night Moves (Arthur Penn, 1975)",
"Pulp Fiction (Quentin Tarantino, 1994)",
"Underworld (Joseph Von Sternberg, 1927)",
"Little Caesar (Mervyn LeRoy, 1930)",
"The Public Enemy (William Wellman, 1931)",
"Scarface (Howard Hawks, 1932)",
"Angels with Dirty Faces (Michael Curtiz, 1938)",
"The Roaring Twenties (Raoul Walsh, 1939)",
"White Heat (Raoul Walsh, 1949)",
"The Asphalt Jungle (John Huston, 1950)",
"Bonnie and Clyde (Arthur Penn, 1967)",
"The Godfather (Francis Ford Coppola, 1972)",
"The Godfather: Part II (Francis Ford Coppola, 1974)",
"Once upon a Time in America (Sergio Leone, 1984)",
"Goodfellas (Martin Scorsese, 1990)",
"Reservoir Dogs (Quentin Tarantino, 1992)",
"Historical and War Films:",
"The Big Parade (King Vidor, 1925) All Quiet on the Western Front (Lewis Milestone, 1930)",
"Young Mr. Lincoln (John Ford, 1939)",
"Mrs. Miniver (William Wyler, 1942)",
"Casablanca (Michael Curtiz, 1942)",
"The Best Years of Our Lives (William Wyler, 1946)",
"From Here to Eternity (Fred Zinnemann, 1953)",
"Paths of Glory (Stanley Kubrick, 1957)",
"Patton (Franklin J. Schaffner, 1970)",
"Full Metal Jacket (Stanley Kubrick, 1987)",
"Schindler's List (Steven Spielberg, 1993)",
"The Thin Red Line (Terrence Malick, 1998)",
"Saving Private Ryan (Steven Spielberg, 1998)",
"Inglourious Basterds (Quentin Tarantino, 2009)",
"The Hurt Locker (Kathryn Bigelow, 2009)",
"Dracula (Tod Browning, 1931)",
"King Kong (Cooper/Schoedsack, 1933)",
"Bride of Frankenstein (James Whale, 1935)",
"Cat People (Jacques Tourneur, 1942)",
"The Seventh Victim (Mark Robson, 1943)",
"The Thing (Christian Nyby, 1951)",
"The Night of the Hunter (Charles Laughton, 1955)",
"Psycho (Alfred Hitchcock, 1960)",
"The Birds (Alfred Hitchcock, 1963)",
"Rosemary's Baby (Roman Polanski, 1968)",
"Night of the Living Dead (George Romero, 1969)",
"The Exorcist (William Friedkin, 1973)",
"Carrie (Brian De Palma, 1978)",
"The Shining (Stanley Kubrick, 1980)",
"The Blair Witch Project (Daniel Myrick/Eduardo Sánchez, 1999)",
"Paranormal Activity (Oren Peli, 2007)",
"Seventh Heaven (Frank Borzage, 1927)",
"Blonde Venus (Josef Von Sternberg, 1932)",
"The Scarlet Empress (Josef von Sternberg, 1934)",
"Stella Dallas (King Vidor, 1937)",
"Stage Door (Gregory La Cava, 1937)",
"Dance, Girl, Dance (Dorothy Arzner, 1940)",
"Rebecca (Alfred Hitchcock, 1940)",
"Now, Voyager (Irving Rapper, 1942)",
"Mildred Pierce (Michael Curtiz, 1945)",
"Letter from an Unknown Woman (Max Ophuls, 1948)",
"All about Eve (Joseph L. Mankiewicz, 1950)",
"The Bad and the Beautiful (Vincente Minnelli, 1952)",
"All That Heaven Allows (Douglas Sirk, 1956)",
"Imitation of Life (Douglas Sirk, 1959)",
"Far from Heaven (Todd Haynes, 2002)",
"The Love Parade (Ernst Lubitsch, 1929)",
"Love Me Tonight (Rouben Mamoulian, 1932)",
"Footlight Parade (Lloyd Bacon/Busby Berkeley, 1933)",
"Top Hat (Mark Sandrich, 1935)",
"Swing Time (George Stevens, 1936)",
"The Wizard of Oz (Victor Fleming, 1939)",
"Meet Me in St. Louis (Roy Mack/Vincente Minnelli, 1945)",
"Easter Parade (Charles Walter, 1948)",
"Singin' in the Rain (Gene Kelly/Stanley Donen, 1952)",
"The Band Wagon (Vincente Minnelli, 1953)",
"Funny Face (Stanley Donen, 1957)",
"West Side Story (Jerome Robbins/Robert Wise, 1961)",
"Cabaret (Bob Fosse, 1972)",
"Moulin Rouge! (Baz Luhrmann, 2001)",
"The Day the Earth Stood Still (Robert Wise, 1951)",
"The War of the Worlds (Byron Haskin, 1953)",
"This Island Earth (Joseph M. Newman, 1955)",
"Forbidden Planet (Fred M. Wilcox, 1956)",
"Invasion of the Body Snatchers (Don Siegel, 1956)",
"Seconds (John Frankenheimer, 1966)",
"2001: A Space Odyssey (Stanley Kubrick, 1968)",
"Star Wars Episode IV: A New Hope (George Lucas, 1977)",
"Blade Runner (Ridley Scott, 1982)",
"Dark City (Alex Proyas, 1998)",
"The Matrix (Andy and Lana Wachowski, 1999)",
"Avatar (James Cameron, 2009)",
"Stagecoach (John Ford, 1939)",
"Canyon Passage (Jacques Tourneur, 1946)",
"Duel in the Sun (King Vidor, 1947)",
"Red River (Howard Hawks, 1948)",
"High Noon (Fred Zinnemann, 1952)",
"Johnny Guitar (Nicholas Ray, 1954)",
"The Man from Laramie (Anthony Mann, 1955)",
"The Searchers (John Ford, 1956)",
"Forty Guns (Samuel Fuller, 1957)",
"Rio Bravo (Howard Hawks, 1959)",
"Ride Lonesome (Budd Boetticher, 1959)",
"The Wild Bunch (Sam Peckinpah, 1969)",
"McCabe and Mrs. Miller (Robert Altman, 1971)",
"Dances with Wolves (Kevin Costner, 1990)",
"Unforgiven (Clint Eastwood, 1992)",
"True Grit (Ethan and Joel Cohn, 2010)",
"The Exiles (Kent MacKenzie, 1961) Two-Lane Blacktop (Monte Hellman, 1971)",
"Badlands (Terrence Malick, 1973)",
"Eraserhead (David Lynch, 1976)",
"Angel City (Jon Jost, 1977)",
"Variety (Bette Gordon, 1980)",
"Stranger than Paradise (Jim Jarmusch, 1984)",
"Henry: Portrait of a Serial Killer (John McNaughton, 1986)",
"sex, lies and videotape (Steven Soderbergh, 1989)",
"Drugstore Cowboy (Gus Van Sant, 1989)",
"Slacker (Richard Linklater, 1991)",
"Smoke (Wayne Wang, 1995)",
"Gummo (Harmony Korine, 1997)",
"George Washington (David Gordon Green, 2000)",
"The Mad Songs of Fernanda Hussein (Jean Gianvito, 2001)",
"Lost in Translation (Sofia Coppola, 2003)",
"Manhatta (Paul Strand/Charles Sheeler, 1921, US)",
"Nanook of the North (Robert Flaherty, 1922, US)",
"Berlin, Symphony of a Big City (Walter Ruttmann, 1927, Ger)",
"Chang (Merian Cooper/Ernest Schoedsack, 1927, US)",
"The Man with the Movie Camera (Dziga Vertov, 1928, USSR)",
"Turksib (Victor Turin, 1929, USSR)",
"Rain (Joris Ivens, 1929, Holland)",
"La Croisière Jaune (Leon Poirer, 1933, Fr)",
"Las Hurdes (Luis Buñuel, 1933, Spain)",
"The Song of Ceylon (Basil Wright, 1934, GB)",
"New Earth (Joris Ivens, 1934, Netherlands)",
"Granton Trawler (John Grierson, 1934, GB)",
"Triumph of the Will (Leni Riefenstahl, 1935, Ger)",
"Housing Problems (Arthur Elton/Edgar Anstey, 1935, GB)",
"Night Mail (Harry Watt/Basil Wright, 1936, GB)",
"The River (Pare Lorentz, 1937, US)",
"The Spanish Earth (Joris Ivens, 1937, US)",
"Olympia (Leni Riefenstahl, 1938, Ger)",
"The City (Willard van Dyke, 1939, US)",
"The Eternal Jew (Fritz Hippler, 1940, Ger)",
"Listen to Britain (Humphrey Jennings/Stewart McAllister, 1941, GB)",
"Why We Fight (Frank Capra, 1942",
"-44, US)",
"The Battle of Russia (Anatole Litvak, 1942, US)",
"Fires Were Started (Humphrey Jennings, 1943, GB)",
"The Battle of San Pietro (John Huston, 1944, US)",
"Let There Be Light (John Huston, 1946, US)",
"Le Sang des bêtes (Georges Franju, 1949, Fr)",
"Kon Tiki (Thor Heyerdahl, 1950, Norway/Sweden)",
"In the Street (Janice Loeb/Helen Levitt/James Agee, 1952, US)",
"Nuit et Brouillard (Alain Resnais, 1955, Fr)",
"We Are the Lambert Boys (Karel Reisz, 1958, UK)",
"Harvest of Shame (CBS with Edward R. Murrow, 1960, US)",
"Chronique d'un Été(Jean Rouch/Edgar Morin, 1961, Fr)",
"Crisis (Richard Leacock, 1963, US)",
"Le Joli Mai (Chris Marker, 1963, Fr)",
"7 Up (Michael Apted, 1963, GB)",
"Point of Order (Emile de Antonio, 1964, US) The War Game (Peter Watkins, 1965, GB)",
"Dead Birds (Robert Gardner, 1965, US)",
"Ordinary Fascism (Mikhail Romm, 1965, USSR)",
"Paris vu par (Collective, 1965, Fr)",
"The Anderson Platoon (Pierre Schoendorffer, 1967, Fr)",
"Primary (Richard Leacock, 1967, US)",
"Portrait of Jason (Shirley Clark, 1967, US)",
"Don't Look Back (D. A. Pennebaker, 1967, US)",
"Titicut Follies (Fred Wiseman, 1967, US)",
"Warrendale (Allan King, 1967, Can)",
"The Hour of the Furnaces (Fernando E. Solanas, 1968, Argentina)",
"Salesman (David and Albert Maysles, 1968, US)",
"Inextinguishable Fire (Harun Farocki, 1969, FRG)",
"Le Chagrin et la pitié (Marcel Ophüls, 1969, Fr)",
"A Married Couple (Allan King, 1969, Can)",
"Hospital (Frederick Wiseman, 1970, US)",
"Woodstock (Michael Wadleigh, 1970, US)",
"China (Michelangelo Antonioni, 1972, It)",
"Grey Gardens (Albert and David Maysles, 1975, US)",
"The Axe Fight (Timothy Asch/Napoleon Chagnon, 1975, US)",
"Mädchen in Wittstock (Volker Koepp, 1975, GDR)",
"The Drugstore (Joris Ivens, 1976, Netherlands)",
"Harlan County, U.S.A. (Barbara Kopple, 1976, US)",
"Germany in Autumn (Collective, 1978, FRG)",
"The Battle of Chile (Patricio Guzman, 1978, Chile)",
"Our Hitler (Hans Jürgen Syberberg, 1977, FRG)",
"Daughter Rite (US, Michelle Citron, 1978, US)",
"The Life and Times of Rosie the Riveter (Connie Field, 1980, US)",
"Talking Heads (Krzystof Kieslowski, 1980, Poland)",
"Wedding Camels (David and Judith MacDougall, 1981, US)",
"Lebensläufe (Winfried Junge, 1981, GDR)",
"A Man When He Is A Man (Valeria Sarmiento, 1982, Chile)",
"Koyaanisqatsi (Godfrey Reggio, 1982, US)",
"The Atomic Cafe (Jayne Loader/Kevin Rafferty/Pierce Rafferty, 1982, US)",
"Sans Soleil (Chris Marker, 1983, Fr)",
"The Times of Harvey Milk (Robert Epstein, 1984, US)",
"Far from Poland (Jill Godmilow, 1984, US)",
"Sherman's March (Ross McElwee, 1985, US)",
"Shoah (Claude Lanzmann, 1985, Fr)",
"Tokyo-ga (Wim Wenders, 1985, FRG)",
"Handsworth Songs (John Akomfrah, 1986, GB)",
"Forest of Bliss (Robert Gardner, 1986, US)",
"The Emperor's Naked Army Marches On (Hara Kazuo, 1987, Jap)",
"The Thin Blue Line (Errol Morris, l988, US)",
"Cane Toads: An Unnatural History (Mark Lewis, 1988, Australia)",
"Une Histoire de vent (Joris Ivens, 1988, Fr/UK/FRG/Netherlands)",
"Histoire(s) du Cinéma (Jean-Luc Godard, 1988-1998, US)",
"Surname Viet Given Name Nam (US, Trinh T. Min-Ha, 1989, US)",
"Roger and Me (Michael Moore, 1989, US)",
"The Wall (Jürgen Böttcher, 1990, FRG)",
"Countdown (Ulrike Ottinger, 1990, FRG)",
"Tongues Tied (Marlon Riggs, 1990, US)",
"28 Up (Michael Apted, 1991, GB)",
"Paris is Burning (Jennie Livingston, 1991, US)",
"Black Harvest (Robin and Bob Anderson, 1992, Australia)",
"Videogram of a Revolution (Harun Farocki, 1992, FRG)",
"Lessons in Darkness (Werner Herzog, 1992, FRG)",
"D'Est (Chantal Akerman, 1993, Belgium)",
"Hoop Dreams (Steve James, 1994, US)",
"Forgotten Silver (Peter Jackson/Costa Botes, 1995, New Zealand)",
"Amsterdam Global Village (Johan van der Keuken, 1997, Netherlands)",
"Megacities (Michael Glawogger, 1998, Austria)",
"Les Glaneurs et la Glaneuse (Agnès Varda, 2000, Fr)",
"Bowling for Colombine (Michael Moore, 2002, US)",
"Etre et avoir (Nicolas Philibert, 2002, Fr)",
"Bus 174 (José Padilla, 2002, Brazil)",
"The Fog of War (Errol Morris, 2003, US)",
"Tie Xi Qu: West of the Tracks (Wang Bing, 2003, China)",
"Bright Leaves (Ross McElwee, 2003, US)",
"Los Angeles Plays Itself (Thom Andersen, 2003)",
"Grizzly Man (Werner Herzog, 2005, US)",
"An Inconvenient Truth (Davis Guggenheim, 2006, US)",
"When the Levees Broke: A Requiem in Four Parts (Spike Lee, 2006, US)",
"Dust (Hartmut Bitomsky, 2007, FRG)",
"My Winnipeg (Guy Maddin, 2007, Canada)",
"Les Plages d'Agnès (Agnès Varda, 2008, Fr)",
"Sweetgrass (Ilisa Barbash and Lucien Castaing-Taylor, 2009, US)",
"The Hasher's Delirium (Emile Cohl, 1906, Fr)",
"Fantasmagoria (Emile Cohl, 1908, Fr)",
"The Dentures (Emile Cohl, 1909, Fr)",
"Gertie the Dinosaur (Winsor McCay, 1909, US)",
"Les Joyeux Microbes (Emile Cohl, 1909)",
"Revenge of a Kinematograph Cameraman (Ladislas Starewicz, 1912, Russia)",
"Gertie the Dinosaur (Winsor McCay, 1914, US)",
"The Sinking of the Lusitania (Winsor McCay, 1918, US)",
"Rhythm 21 (Hans Richter, 1921, Germany)",
"Steamboat Wille (Ub lwerks/Walt Disney, 1928, US)",
"Jack and the Beanstalk (Max and David Fleischer, 1931, US)",
"The Three Little Pigs (Walt Disney, 1933, US)",
"Night on Bald Mountain (Alexandre Alexeieff and Claire Parker, 1933)",
"Betty Boop’s Rise to Fame (Max Fleischer, 1934, US)",
"Colour Box (Len Lye, 1935, GB)",
"Snow White and the Seven Dwarfs (Walt Disney, 1937, US)",
"A Roadrunner cartoon (Chuck Jones, US)",
"A “Tom and Jerry” cartoon (Tex Avery, US)",
"A “Woody Woodpecker” cartoon (Walter Lanz, US)",
"Motion Painting No.1 ( Oskar Fischinger, 1947, US)",
"Begone Dull Care (Norman McLaren, 1949, Canada)",
"Neighbors (Norman McLaren, 1952, Canada)",
"Jazz Dance (Roger Tilton, 1954, USA)",
"A Man and His Dog Out for Air (Robert Breer, 1958, US)",
"The Fabulous Adventures of Jules Verne (Karel Zeman, 1958, Czech)",
"Colour Rhapsody (Mary Ellen Bute, 1958)",
"Moonbird (John and Faith Hubley, 1959, US)",
"Yantra (1960), Lapis (1966), Permutations (1967) (John and James Whitney, US)",
"Allures (Jordon Belsen, 1961, US)",
"The Flying Man (George Dunning, 1962, US)",
"The Hole (John Hubley, 1962, US)",
"Mothlight (Stan Brakhage, 1963, US)",
"Rhinoceros (Jan Lenica, 1963, Poland)",
"Love (Yoji Kuri, 1963, Japan)",
"Jeux des Anges (Walerian Borowczyk, 1964)",
"The Hand (Jiri Trnka, 1965, Czech)",
"Water and Power (Pat O’Neill, 1967, US)",
"Fritz the Cat (Ralph Bakshi, 1972, US)",
"Mirror People (Kathy Rose, 1974, US)",
"The Street (Caroline Leaf, 1976, Canada)",
"La Traversée de l’Atlantique à la Rame (Jean-Francois Laguionie, 1978, Fr)",
"Asparagus (Suzanne Pitt, 1978, US)",
"Tale of Tales (Yuri Norstein, 1979, USSR)",
"Tango (Zbig Rybczynski, 1981, Poland)",
"Dimensions of Dialogue (Jan Svankmajer, 1982, Czech)",
"L’Ange (Patrick Bokanowski, 1982, Fr)",
"Nausicaä of the Valley of the Wind (Hayao Miyazaki, 1984, Japan)",
"Luxo Jr. (John Lasseter, 1986, US)",
"The Street of Crocodiles (Brothers Quay, 1986, GB)",
"The Dante Quartet (Stan Brackage, 1987, US)",
"Steps (Zbig Rybczynski, 1987, Poland)",
"Early Abstractions (Harry Smith, 1987, US)",
"Feet of Song (Erika Russell, 1988, GB)",
"My Neighbor Totoro (Hayao Miyazaki, 1988, Japan)",
"Alternative Fringe (Candy Guard, 1988, GB)",
"The Public Voice (Leif Marcussen, 1989, Den)",
"Repete (Mikaela Pavlatova, 1995, Czech)",
"Princess Mononoke (Hayao Miyazaki, 1999, Japan)",
"La Souriante Madame Beudet (Germaine Dulac, 1923, Fr)",
"Paris qui dort (René Clair, 1923, Fr)",
"Le Retour à la raison (Man Ray, 1923, Fr)",
"Ballet Mécanique (Fernand Leger, 1924, Fr)",
"Entr'acte (René Clair, 1924, Fr)",
"Menilmontant (Dmitri Kirsanov, 1925, Fr)",
"Anémic Cinéma (Marcel Duchamp, 1926, Fr)",
"La Cocquille et le Clergyman (Germaine Dulac, 1927, Fr)",
"Emak Bakia (May Ray, 1927, Fr)",
"La Chute de la Maison d'Usher (Jean Epstein, 1928, Fr)",
"L'Etoile de Mer (Man Ray, 1928, Fr)",
"Un Chien Andalou (Luis Buñuel/Salvador Dali, 1929, Fr)",
"A Propos de Nice (Jean Vigo, 1929, Fr)",
"Meshes of the Afternoon (Maya Deren, 1943, US)",
"Pacific 231 (Jean Mitry, 1949, Fr)",
"Images pour Debussy (Jean Mitry, 1951, Fr)",
"Un Chant d’Amour (Jean Genet, 1952, Fr)",
"Adebar (Peter Kubelka, 1957, Austria)",
"Schwacheter (Peter Kubelka, 1958, Austria)",
"Anticipation of the Night (Stan Brakhage, 1958, US)",
"A Movie (Bruce Conner, 1958, US)",
"Window Water Baby Moving (Stan Brakhage, 1959, US)",
"Star Man (Stan Brakhage, 1961-64, US)",
"The Connection (Shirley Clark, 1961, US)",
"Flaming Creatures (Jack Smith, 1962, US)",
"Scorpio Rising (Kenneth Anger, 1963, US)",
"Film (Samuel Beckett/ Alan Schneider, 1965, Fr)",
"Chelsea Girls (Andy Warhol, 1966, US)",
"Fuses (Carolee Schneeman, 1967, US)",
"Unsere Afrikareise (Peter Kubelka, 1966, Austria)",
"Castro Street (Bruce Baillie, 1966, US)",
"Wavelength (Michael Snow, 1967, Canada)",
"Chelsea Girls (Andy Warhol, 1967, US)",
"69 (Robert Breer, 1968, US)",
"T.O.U.C.H.I.N.G. (Paul Sharits, 1968, US)",
"Zorn's Lemma (Hollis Frampton, 1970, US)",
"Serene Velocity (Ernie Gehr, 1970, US)",
"Tom, Tom, The Piper’s Son (Ken Jacobs, 1971, US)",
"Nostalgia (Hollis Frampton, 1971, US)",
"Reminiscences of a Journey to Lithuania (Jonas Mekas, 1971-72, US)",
"Rameau's Nephew by Diderot (Thanx to Dennis Young) (Michael Snow, 1974, Canada)",
"Semiotics of the Kitchen (Martha Rosler, 1975, USA)",
"Riddles of the Sphinx (Peter Wollen/Laura Mulvey, 1977, UK)",
"One Way Boogie Woogie (James Benning, 1977, US)",
"One Way or Another (Sara Gomez, 1978, Cuba)",
"Technology Transformation: Wonder Woman (Dara Birnbaum, 1978, USA)",
"Thriller (Sally Potter, 1979, GB)",
"Journeys from Berlin/1971 (Yvonne Rainer, 1980, US)",
"Born in Flames (Lizzie Borden, 1982, US)",
"Material Girl (Mary Lambert, 1984, USA)",
"Ties That Bind (Su Friedrich, 1984, US)",
"Privilege (Yvonne Rainer, 1990, US)",
"Blue (Derek Jarman, 1993, GB)",
"The Best of Ernie Kovacs (Ernie Kovacs, 1957ff., US)",
"Stamping in My Studio (Bruce Nauman, 1968, US)",
"Self Burial (Keith Arnatt, 1969, FRG)",
"Hello (Allan Kaprow, 1969, US)",
"TV Interruptions (David Hall, 1971, US)",
"I Will Not Make Any More Boring Art (John Baldessari, 1971, US)",
"Centers (Vito Acconti, 1971, US)",
"Vertical Roll (Joan Jonas, 1972, US)",
"Past Future/Split Attention (Dan Graham, 1972, US)",
"Selected Works: Reel 4 (William Wegman, USA, 1972)",
"Theme Song (Vito Acconci, 1973, US)",
"Three Transitions (Peter Campus, 1973, US)",
"Global Groove (Nam June Paik, 1973, US)",
"TV Delivers People (Richard Serra/Nancy Holt, 1973, US)",
"TV Ad (Chris Burden, 1973, US)",
"The Meaning of Various News Photos (John Baldessari, 1973, US)",
"Children’s Tapes (Terry Fox, 1974, US)",
"Ball (William Wegman, 1974, US)",
"Body Music (Charlemagne Palestine, 1974, US)",
"The Eternal Frame (T.R. Uthco and Ant Farm, 1975, US)",
"My Father (Shigeko Kubota, 1975, Japan)",
"Probably the World’s Smallest TV Station (Media Bus, 1975, US)",
"Upset Stomach—Fast (Paulo Herkenhoff, 1975, Brazil)",
"Revolve (Nancy Holt, 1977, US)",
"The Red Tapes (Vito Acconci, 1977, US)",
"Cage, Wire (Sonia Andrade, 1977, US)",
"The Reflecting Pool (Bill Viola, 1977-79, US)",
"Technology/Transformation (Wonder Woman) (Dara Birnbaum, 1978, US)",
"Kiss the Girls and Make Them Cry (Dara Birnbaum, 1979, US)",
"Hearts (Barbara Buckner, 1979, US)",
"Sunstone (Ed Emshwiller, 1979, US)",
"Beneath the Skin (Cecelia Condit, 1981, US)",
"The Looking Glass (Juan Downey, 1981, US)",
"Meta Mayan (Edin Vélez, 1981, US)",
"Smothering Dreams (Daniel Reeves, 1981, US)",
"Casual Shopper (Judith Barry, 1981, US)",
"Rock My Religion (Dan Graham, 1982-84, US)",
"Ohio to Giverny: Memory of Light (Mary Lucier, 1983, US)",
"Subatomic Babies (Shalom Gorewitz, 1983, US)",
"Anthem (Bill Viola, 1983, US)",
"Reasons for Knocking at an Empty House (Bill Viola, 1983, US)",
"Sabda (Daniel Reeves, 1984, US)",
"Der Riese (Michael Klier, 1984, FRG)",
"Reverse Television (Bill Viola, 1984, US)",
"Why Do Things Get in a Muddle? (Come on Petunia) (Gary Hill, 1984, US)",
"Incidence of Catastrophe (Gary Hill, 1987-8, US)",
"Not a Jealous Bone (Cecelia Condit, 1987, US)",
"Art of Memory (Woody and Steina Vasulka, 1987, US)",
"Berlin: Tourist Journal (Ken Kobland, 1988, US)",
"Some Aspect of a Shared Lifestyle (Gregg Bordowitz, 1986, US)",
"Mike (Michael Smith, 1987, US)",
"Political Advertisements II: 1956-1988 (Muntadas, 1988, US)",
"Volcano Saga (Joan Jonas, 1989, US)",
"Site Recite (A Prologue) (Gary Hill, 1989, US)",
"Like a Prayer (DIVA TV, 1989, US)",
"A TV Dante (Peter Greenaway, 1989, GB)",
"Jollies (Sadie Benning, 1990, US)",
"Desire Incorporated (Lynn Herschman, 1990, US)",
"The Passing (Bill Viola, 1991, US)",
"1989 – The Revolution on Television - The Real Power of TV (Gusztáv Hámos, 1991, FRG)",
"Corps étranger (Mona Hatoum, 1994, UK)",
"Oh, Rapunzel (Cecelia Condit, 1996, US)",
"The B.C. Corporate Story (Bernadette Corporation, 1996, US)",
"2 into 1 (Gillian Wearing, 1997, US)",
"Presenta (Yoshua Okón, 1998, Mexico)",
"Involuntary Reception (Kristin Lucas, 2000, US)",
"Trembling Time (Yael Bartana, 2001, Israel)",
"La Tombola (Ximena Cuevas, 2001, Mexico)",
"Still Life (Sam Taylor-Wood, 2001, UK)",
"My Sneakers (Michael Blum, 2001, Israel)",
"Hostage: The Bachar Tapes (The Atlas Group/Walid Raad, 200, Lebanon)",
"Mom and Me Watching Zoolander (Anne Walsh, 2002, US)",
"10 Minutes of Collective Activity (Sharon Hayes, 2003, US)",
"Baghdad in No Particular Order (Paul Chan, 2003, US)",
"Stoned & Dethroned (Slater Bradley, 2004, US)",
"30 Seconds Hate (Bryan Boyce, 2004, US)",
"Returning a Sound (Jennifer Allora/Guillermo Calzadilla, 2004, US)",
"Miranda July Videoworks: Volume 1 (Miranda July, 2005, US)"
]
