var CRITERION_FILMS = [ 
"Portrait of a Lady on Fire (Céline Sciamma, 2019)",
"Marriage Story (Noah Baumbach, 2019)",
"Parasite (Bong Joon-ho, 2019)",
"The Irishman (Martin Scorsese, 2019)",
"Rolling Thunder Revue: A Bob Dylan Story by Martin Scorsese (Martin Scorsese, 2019)",
"Cold War (Paweł Pawlikowski, 2018)",
"Roma (Alfonso Cuarón, 2018)",
"Wildlife (Paul Dano, 2018)",
"Minding the Gap (Bing Liu, 2018)",
"The Other Side of Hope (Aki Kaurismäki, 2017)",
"24 Frames (Abbas Kiarostami, 2017)",
"Let the Sunshine In (Claire Denis, 2017)",
"Cameraperson (Kirsten Johnson, 2016)",
"Certain Women (Kelly Reichardt, 2016)",
"David Lynch: The Art Life (Olivia Neergaard-Holm, Rick Barnes, John Nguyen, 2016)",
"Personal Shopper (Olivier Assayas, 2016)",
"I, Daniel Blake (Ken Loach, 2016)",
"Graduation (Cristian Mungiu, 2016)",
"Ingrid Bergman: In Her Own Words (Stig Björkman, 2015)",
"Heart of a Dog (Laurie Anderson, 2015)",
"45 Years (Andrew Haigh, 2015)",
"Dheepan (Jacques Audiard, 2015)",
"The Lure (Agnieszka Smoczyńska, 2015)",
"A Master Builder (Jonathan Demme, 2014)",
"Two Days, One Night (Jean-Pierre Dardenne, Luc Dardenne, 2014)",
"Phoenix (Christian Petzold, 2014)",
"Clouds of Sils Maria (Olivier Assayas, 2014)",
"Boyhood (Richard Linklater, 2014)",
"The Grand Budapest Hotel (Wes Anderson, 2014)",
"Frances Ha (Noah Baumbach, 2013)",
"Blue Is the Warmest Color (Abdellatif Kechiche, 2013)",
"The Great Beauty (Paolo Sorrentino, 2013)",
"Jellyfish Eyes (Takashi Murakami, 2013)",
"Inside Llewyn Davis (Joel and Ethan Coen, 2013)",
"Before Midnight (Richard Linklater, 2013)",
"Like Someone in Love (Abbas Kiarostami, 2012)",
"Moonrise Kingdom (Wes Anderson, 2012)",
"Beyond the Hills (Cristian Mungiu, 2012)",
"Le Havre (Aki Kaurismäki, 2011)",
"Weekend (Andrew Haigh, 2011)",
"The Forgiveness of Blood (Joshua Marston, 2011)",
"Pina (Wim Wenders, 2011)",
"The Kid with a Bike (Jean-Pierre Dardenne, Luc Dardenne, 2011)",
"The Tree of Life (Terrence Malick, 2011)",
"Life During Wartime (Todd Solondz, 2010)",
"Carlos (Olivier Assayas, 2010)",
"Tiny Furniture[15] (Lena Dunham, 2010)",
"Certified Copy[16] (Abbas Kiarostami, 2010)",
"And Everything Is Going Fine (Steven Soderbergh, 2010)",
"Antichrist (Lars von Trier, 2009)",
"Fish Tank (Andrea Arnold, 2009)",
"White Material (Claire Denis, 2009)",
"Fantastic Mr. Fox (Wes Anderson, 2009)",
"The Curious Case of Benjamin Button (David Fincher, 2008)",
"A Christmas Tale (Arnaud Desplechin, 2008)",
"Gomorrah (Matteo Garrone, 2008)",
"Che (Steven Soderbergh, 2008)",
"Revanche (Götz Spielmann, 2008)",
"Hunger (Steve McQueen, 2008)",
"Summer Hours (Olivier Assayas, 2008)",
"Everlasting Moments (Jan Troell, 2008)",
"Still Walking (Hirokazu Kore-eda, 2008)",
"The Secret of the Grain (Abdellatif Kechiche, 2007)",
"The Darjeeling Limited (Wes Anderson, 2007)",
"Secret Sunshine (Lee Chang-dong, 2007)",
"My Winnipeg (Guy Maddin, 2007)",
"4 Months, 3 Weeks and 2 Days (Cristian Mungiu, 2007)",
"Chop Shop (Ramin Bahrani, 2007)",
"The Beales of Grey Gardens (Albert Maysles, David Maysles, 2006)",
"Brand upon the Brain! (Guy Maddin, 2006)",
"Bergman Island (Marie Nyreröd, 2006)",
"Colossal Youth (Pedro Costa, 2006)",
"Pan's Labyrinth (Guillermo del Toro, 2006)",
"Old Joy (Kelly Reichardt, 2006)",
"The New World (Terrence Malick, 2005)",
"The Squid and the Whale (Noah Baumbach, 2005)",
"Me and You and Everyone We Know (Miranda July, 2005)",
"Man Push Cart (Ramin Bahrani, 2005)",
"The Life Aquatic with Steve Zissou (Wes Anderson, 2004)",
"Before Sunset (Richard Linklater, 2004)",
"Naqoyqatsi (Godfrey Reggio, 2002)",
"Punch-Drunk Love (Paul Thomas Anderson, 2002)",
"Bowling for Columbine (Michael Moore, 2002)",
"Japón (Carlos Reygadas, 2002)",
"The Royal Tenenbaums (Wes Anderson, 2001)",
"Fat Girl (Catherine Breillat, 2001)",
"Monsoon Wedding (Mira Nair, 2001)",
"The Devil's Backbone (Guillermo del Toro, 2001)",
"Y tu mamá también (Alfonso Cuarón, 2001)",
"La Ciénaga (Lucrecia Martel, 2001)",
"Mulholland Dr. (David Lynch, 2001)",
"Ghost World (Terry Zwigoff, 2001)",
"The Piano Teacher (Michael Haneke, 2001)",
"Hedwig and the Angry Inch (John Cameron Mitchell, 2001)",
"In the Mood for Love (Wong Kar-wai, 2000)",
"Traffic (Steven Soderbergh, 2000)",
"George Washington (David Gordon Green, 2000)",
"A Constant Forge (Charles Kiselyak, 2000)",
"Yi Yi (Edward Yang, 2000)",
"In Vanda's Room (Pedro Costa, 2000)",
"Code Unknown (Michael Haneke, 2000)",
"Mysterious Object at Noon (Apichatpong Weerasethakul, 2000)",
"Bamboozled (Spike Lee, 2000)",
"Amores perros (Alejandro González Iñárritu, 2000)",
"Ratcatcher (Lynne Ramsay, 1999)",
"Ride with the Devil (Ang Lee, 1999)",
"Topsy-Turvy (Mike Leigh, 1999)",
"Being John Malkovich (Spike Jonze, 1999)",
"Rosetta (Jean-Pierre Dardenne, Luc Dardenne, 1999)",
"Following (Christopher Nolan, 1999)",
"Buena Vista Social Club (Wim Wenders, 1999)",
"Election (Alexander Payne, 1999)",
"The Virgin Suicides (Sofia Coppola, 1999)",
"L'Humanité (Bruno Dumont, 1999)",
"All About My Mother (Pedro Almodóvar, 1999)",
"Beau Travail (Claire Denis, 1999)",
"Ghost Dog: The Way of the Samurai (Jim Jarmusch, 1999)",
"Armageddon (Michael Bay, 1998)",
"Rushmore (Wes Anderson, 1998)",
"Fear and Loathing in Las Vegas (Terry Gilliam, 1998)",
"The Last Days of Disco (Whit Stillman, 1998)",
"The Thin Red Line (Terrence Malick, 1998)",
"Taste of Cherry (Abbas Kiarostami, 1997)",
"Insomnia (Erik Skjoldbjærg, 1997)",
"Chasing Amy (Kevin Smith, 1997)",
"The Ice Storm (Ang Lee, 1997)",
"Letters from Fontainhas:, Three Films by Pedro Costa (Pedro Costa, 1997–2006)",
"Ossos (Pedro Costa, 1997)",
"Gray's Anatomy (Steven Soderbergh, 1997)",
"The Game (David Fincher, 1997)",
"Funny Games (Michael Haneke, 1997)",
"La vie de Jésus (Bruno Dumont, 1997)",
"The Rock (Michael Bay, 1996)",
"Schizopolis (Steven Soderbergh, 1996)",
"Bottle Rocket (Wes Anderson, 1996)",
"La promesse (Jean-Pierre Dardenne, Luc Dardenne, 1996)",
"Breaking the Waves (Lars von Trier, 1996)",
"When We Were Kings (Leon Gast, 1996)",
"The Daytrippers (Greg Mottola, 1996)",
"Crash (David Cronenberg, 1996)",
"Secrets & Lies (Mike Leigh, 1996)",
"Carl Th. Dreyer—My Metier (Torben Skjodt Jensen, 1995)",
"Kicking and Screaming (Noah Baumbach, 1995)",
"La haine (Mathieu Kassovitz, 1995)",
"Crumb (Terry Zwigoff, 1995)",
"Safe (Todd Haynes, 1995)",
"The Before Trilogy (Richard Linklater, 1995–2013)",
"Before Sunrise (Richard Linklater, 1995)",
"Dead Man (Jim Jarmusch, 1995)",
"Hoop Dreams (Steve James, 1994)",
"Clean, Shaven (Lodge Kerrigan, 1994)",
"Before the Rain (Milčo Mančevski, 1994)",
"Chungking Express (Wong Kar-wai, 1994)",
"Three Colors: White (Krzysztof Kieślowski, 1994)",
"Three Colors: Red (Krzysztof Kieślowski, 1994)",
"Vanya on 42nd Street (Louis Malle, 1994)",
"Shallow Grave (Danny Boyle, 1994)",
"Barcelona (Whit Stillman, 1994)",
"Cold Water (Olivier Assayas, 1994)",
"Through the Olive Trees (Abbas Kiarostami, 1994)",
"Short Cuts (Robert Altman, 1993)",
"Naked (Mike Leigh, 1993)",
"Dazed and Confused (Richard Linklater, 1993)",
"Cronos (Guillermo del Toro, 1993)",
"Three Colors (Krzysztof Kieślowski, 1993 & 1994)",
"Three Colors: Blue (Krzysztof Kieślowski, 1993)",
"The War Room (D. A. Pennebaker, Chris Hegedus, 1993)",
"King of the Hill[20] (Steven Soderbergh, 1993)",
"The Age of Innocence (Martin Scorsese, 1993)",
"Hard Boiled (John Woo, 1992)",
"Fishing with John (John Lurie, 1992)",
"Man Bites Dog (Rémy Belvaux, André Bonzel, Benoît Poelvoorde, 1992)",
"Howards End (James Ivory, 1992)",
"La vie de bohème (Aki Kaurismäki, 1992)",
"The Long Day Closes (Terence Davies, 1992)",
"The Player (Robert Altman, 1992)",
"Twin Peaks: Fire Walk with Me (David Lynch, 1992)",
"And Life Goes On (Abbas Kiarostami, 1992)",
"The Silence of the Lambs (Jonathan Demme, 1991)",
"Naked Lunch (David Cronenberg, 1991)",
"Slacker[2] (Richard Linklater, 1991)",
"My Own Private Idaho (Gus Van Sant, 1991)",
"Sólo con tu pareja (Alfonso Cuarón, 1991)",
"The Double Life of Véronique (Krzysztof Kieślowski, 1991)",
"Night on Earth (Jim Jarmusch, 1991)",
"Europa (Lars von Trier, 1991)",
"Homicide (David Mamet, 1991)",
"A Brief History of Time (Errol Morris, 1991)",
"The Fisher King (Terry Gilliam, 1991)",
"A Brighter Summer Day (Edward Yang, 1991)",
"Europa Europa (Agnieszka Holland, 1991)",
"The Inland Sea (Lucille Carra, 1991)",
"Until the End of the World (Wim Wenders, 1991)",
"The Prince of Tides (Barbra Streisand, 1991)",
"Defending Your Life (Albert Brooks, 1991)",
"An Angel at My Table (Jane Campion, 1990)",
"Metropolitan (Whit Stillman, 1990)",
"3 Films by Louis Malle (Louis Malle, 1990)",
"Close-Up[9] (Abbas Kiarostami, 1990)",
"Life Is Sweet (Mike Leigh, 1990)",
"Tie Me Up! Tie Me Down! (Pedro Almodóvar, 1990)",
"Mister Johnson (Bruce Beresford, 1990)",
"Akira Kurosawa's Dreams (Akira Kurosawa, 1990)",
"To Sleep with Anger (Charles Burnett, 1990)",
"Paris Is Burning (Jennie Livingston, 1990)",
"The Comfort of Strangers (Paul Schrader, 1990)",
"The Killer (John Woo, 1989)",
"For All Mankind (Al Reinert, 1989)",
"Do the Right Thing (Spike Lee, 1989)",
"Sweetie (Jane Campion, 1989)",
"Mystery Train (Jim Jarmusch, 1989)",
"Revenge (Ermek Shinarbaev, 1989)",
"Sex, Lies, and Videotape (Steven Soderbergh, 1989)",
"A Dry White Season (Euzhan Palcy, 1989)",
"Dead Ringers (David Cronenberg, 1988)",
"The Unbearable Lightness of Being (Philip Kaufman, 1988)",
"The Last Temptation of Christ (Martin Scorsese, 1988)",
"How to Get Ahead in Advertising (Bruce Robinson, 1988)",
"The Vanishing (George Sluizer, 1988)",
"Tanner '88 (Robert Altman, 1988)",
"Powaqqatsi (Godfrey Reggio, 1988)",
"The Thin Blue Line (Errol Morris, 1988)",
"Dekalog (Krzysztof Kieślowski, 1988)",
"Women on the Verge of a Nervous Breakdown (Pedro Almodóvar, 1988)",
"Bull Durham (Ron Shelton, 1988)",
"Police Story 2 (Jackie Chan, 1988)",
"RoboCop (Paul Verhoeven, 1987)",
"Au revoir les enfants (Louis Malle, 1987)",
"Border Radio (Allison Anders, Dean Lent, Kurt Voss, 1987)",
"House of Games (David Mamet, 1987)",
"The Last Emperor (Bernardo Bertolucci, 1987)",
"Walker (Alex Cox, 1987)",
"Wings of Desire (Wim Wenders, 1987)",
"Broadcast News (James L. Brooks, 1987)",
"Babette's Feast (Gabriel Axel, 1987)",
"The Princess Bride (Rob Reiner, 1987)",
"Where Is the Friend's House? (Abbas Kiarostami, 1987)",
"Matewan (John Sayles, 1987)",
"Moonstruck (Norman Jewison, 1987)",
"Sid & Nancy (Alex Cox, 1986)",
"Mona Lisa (Neil Jordan, 1986)",
"Withnail and I (Bruce Robinson, 1986)",
"Down by Law (Jim Jarmusch, 1986)",
"Jimi Plays Monterey & Shake! Otis at Monterey (D. A. Pennebaker, 1986)",
"Something Wild (Jonathan Demme, 1986)",
"True Stories (David Byrne, 1986)",
"Blue Velvet (David Lynch, 1986)",
"Betty Blue (Jean-Jacques Beineix, 1986)",
"Brazil (Terry Gilliam, 1985)",
"Vagabond (Agnès Varda, 1985)",
"My Life as a Dog (Lasse Hallström, 1985)",
"Ran (Akira Kurosawa, 1985)",
"Mala Noche (Gus Van Sant, 1985)",
"Mishima: A Life in Four Chapters (Paul Schrader, 1985)",
"Louie Bluie (Terry Zwigoff, 1985)",
"Insignificance (Nicolas Roeg, 1985)",
"Shoah (Claude Lanzmann, 1985)",
"My Beautiful Laundrette (Stephen Frears, 1985)",
"A Room with a View (James Ivory, 1985)",
"Tampopo (Juzo Itami, 1985)",
"Taipei Story (Edward Yang, 1985)",
"Lost in America (Albert Brooks, 1985)",
"Desert Hearts (Donna Deitch, 1985)",
"The Breakfast Club (John Hughes, 1985)",
"Police Story (Jackie Chan, 1985)",
"Come and See (Elem Klimov, 1985)",
"Smooth Talk (Joyce Chopra, 1985)",
"This Is Spinal Tap (Rob Reiner, 1984)",
"And the Ship Sails On (Federico Fellini, 1984)",
"The Element of Crime (Lars von Trier, 1984)",
"Secret Honor (Robert Altman, 1984)",
"Stranger Than Paradise[4] (Jim Jarmusch, 1984)",
"Under the Volcano (John Huston, 1984)",
"Antonio Gaudi (Hiroshi Teshigahara, 1984)",
"The Hit (Stephen Frears, 1984)",
"Paris, Texas (Wim Wenders, 1984)",
"The Times of Harvey Milk (Robert Epstein, 1984)",
"Repo Man (Alex Cox, 1984)",
"Love Streams (John Cassavetes, 1984)",
"Blood Simple (Joel and Ethan Coen, 1984)",
"Meantime (Mike Leigh, 1984)",
"1984 (Michael Radford, 1984)",
"Videodrome (David Cronenberg, 1983)",
"À nos amours (Maurice Pialat, 1983)",
"El Norte (Gregory Nava, 1983)",
"Danton (Andrzej Wajda, 1983)",
"Merry Christmas, Mr. Lawrence (Nagisa Oshima, 1983)",
"The Makioka Sisters (Kon Ichikawa, 1983)",
"The Qatsi Trilogy (Godfrey Reggio, 1983–2002)",
"Koyaanisqatsi (Godfrey Reggio, 1983)",
"The Big Chill (Lawrence Kasdan, 1983)",
"Burroughs: The Movie (Howard Brookner, 1983)",
"Rumble Fish (Francis Ford Coppola, 1983)",
"L'argent (Robert Bresson, 1983)",
"El Sur (Víctor Erice, 1983)",
"Local Hero (Bill Forsyth, 1983)",
"Beastie Boys Video Anthology (David Perez, Ari Marcopoulos, Nathanial Hörnblowér, Spike Jonze, Adam Bernstein, Evan Bernard, Tamra Davis, 1982–2000)",
"Veronika Voss (Rainer Werner Fassbinder, 1982)",
"Fanny and Alexander Box Set (Ingmar Bergman, 1982)",
"Fanny and Alexander — The Television Version (Ingmar Bergman, 1982)",
"Fanny and Alexander — The Theatrical Version (Ingmar Bergman, 1982)",
"The Making of Fanny and Alexander (Ingmar Bergman, 1982)",
"Burden of Dreams (Les Blank, 1982)",
"Missing (Costa Gavras, 1982)",
"White Dog (Samuel Fuller, 1982)",
"Identification of a Woman (Michelangelo Antonioni, 1982)",
"Eating Raoul (Paul Bartel, 1982)",
"Une chambre en ville (Jacques Demy, 1982)",
"Tootsie (Sydney Pollack, 1982)",
"The Ballad of Gregorio Cortez (Robert M. Young, 1982)",
"Smithereens (Susan Seidelman, 1982)",
"Time Bandits (Terry Gilliam, 1981)",
"Coup de torchon (Bertrand Tavernier, 1981)",
"Lola (Rainer Werner Fassbinder, 1981)",
"My Dinner with André (Louis Malle, 1981)",
"Blow Out[11] (Brian De Palma, 1981)",
"Trances (Ahmed El Maânouni, 1981)",
"Thief (Michael Mann, 1981)",
"Scanners[21] (David Cronenberg, 1981)",
"Vernon, Florida (Errol Morris, 1981)",
"The French Lieutenant's Woman (Karel Reisz, 1981)",
"Blind Chance (Krzysztof Kieślowski, 1981)",
"Polyester (John Waters, 1981)",
"Pixote (Héctor Babenco, 1981)",
"The Long Good Friday (John Mackenzie, 1980)",
"Hopscotch (Ronald Neame, 1980)",
"Kagemusha (Akira Kurosawa, 1980)",
"Bad Timing (Nicolas Roeg, 1980)",
"Berlin Alexanderplatz[5] (Rainer Werner Fassbinder, 1980)",
"The Last Metro (François Truffaut, 1980)",
"Heaven's Gate (Michael Cimino, 1980)",
"Every Man for Himself (Jean-Luc Godard, 1980)",
"Dressed to Kill (Brian De Palma, 1980)",
"Breaker Morant (Bruce Beresford, 1980)",
"The Elephant Man (David Lynch, 1980)",
"Monty Python's Life of Brian (Terry Jones, 1979)",
"Love on the Run (François Truffaut, 1979)",
"The Tin Drum (Volker Schlöndorff, 1979)",
"Vengeance Is Mine (Shohei Imamura, 1979)",
"Wise Blood (John Huston, 1979)",
"Quadrophenia (Franc Roddam, 1979)",
"Tess (Roman Polanski, 1979)",
"All That Jazz (Bob Fosse, 1979)",
"The Rose (Mark Rydell, 1979)",
"The Black Stallion (Carroll Ballard, 1979)",
"The Brood (David Cronenberg, 1979)",
"The In-Laws (Arthur Hiller, 1979)",
"Being There (Hal Ashby, 1979)",
"Stalker (Andrei Tarkovsky, 1979)",
"My Brilliant Career (Gillian Armstrong, 1979)",
"Town Bloody Hall (Chris Hegedus, D. A. Pennebaker, 1979)",
"Christ Stopped at Eboli (Francesco Rosi, 1979)",
"Autumn Sonata (Ingmar Bergman, 1978)",
"Jubilee (Derek Jarman, 1978)",
"The BRD Trilogy (Rainer Werner Fassbinder, 1978–1981)",
"The Marriage of Maria Braun (Rainer Werner Fassbinder, 1978)",
"Koko: A Talking Gorilla (Barbet Schroeder, 1978)",
"Days of Heaven (Terrence Malick, 1978)",
"Empire of Passion (Nagisa Oshima, 1978)",
"La Cage aux Folles (Edouard Molinaro, 1978)",
"Watership Down (Martin Rosen, 1978)",
"Gates of Heaven (Errol Morris, 1978)",
"The Tree of Wooden Clogs (Ermanno Olmi, 1978)",
"I Wanna Hold Your Hand (Robert Zemeckis, 1978)",
"An Unmarried Woman (Paul Mazursky, 1978)",
"Girlfriends (Claudia Weill, 1978)",
"The Last Wave (Peter Weir, 1977)",
"That Obscure Object of Desire (Luis Buñuel, 1977)",
"3 Women (Robert Altman, 1977)",
"Opening Night (John Cassavetes, 1977)",
"House (Nobuhiko Obayashi, 1977)",
"¡Alambrista! (Robert M. Young, 1977)",
"Eraserhead (David Lynch, 1977)",
"A Special Day (Ettore Scola, 1977)",
"The American Friend (Wim Wenders, 1977)",
"Jabberwocky (Terry Gilliam, 1977)",
"One Sings, the Other Doesn't (Agnès Varda, 1977)",
"The Ascent (Larisa Shepitko, 1977)",
"Grey Gardens (David Maysles, Albert Maysles, Muffie Meyer, Susan Froemke, Ellen Hovde, 1976)",
"Coup de grâce (Volker Schlöndorff, 1976)",
"The Killing of a Chinese Bookie (John Cassavetes, 1976)",
"The Man Who Fell to Earth (Nicolas Roeg, 1976)",
"Harlan County, USA (Barbara Kopple, 1976)",
"Cría cuervos ... (Carlos Saura, 1976)",
"In the Realm of the Senses (Nagisa Oshima, 1976)",
"Kings of the Road (Wim Wenders, 1976)",
"Canoa: A Shameful Memory (Felipe Cazals, 1976)",
"Insiang (Lino Brocka, 1976)",
"Mikey and Nicky (Elaine May, 1976)",
"Salò, or The 120 Days of Sodom (Pier Paolo Pasolini, 1975)",
"Picnic at Hanging Rock [22] (Peter Weir, 1975)",
"The Magic Flute (Ingmar Bergman, 1975)",
"The Lost Honor of Katharina Blum (Margarethe von Trotta, Volker Schlöndorff, 1975)",
"F for Fake (Orson Welles, 1975)",
"Overlord (Stuart Cooper, 1975)",
"Jeanne Dielman, 23 quai du Commerce, 1080 Bruxelles (Chantal Akerman, 1975)",
"Black Moon (Louis Malle, 1975)",
"Nashville (Robert Altman, 1975)",
"Wrong Move (Wim Wenders, 1975)",
"Fox and His Friends (Rainer Werner Fassbinder, 1975)",
"Barry Lyndon (Stanley Kubrick, 1975)",
"Manila in the Claws of Light (Lino Brocka, 1975)",
"Shampoo (Hal Ashby, 1975)",
"Amarcord (Federico Fellini, 1974)",
"Blood for Dracula (Paul Morrissey, 1974)",
"The Night Porter (Liliana Cavani, 1974)",
"General Idi Amin Dada: A Self Portrait (Barbet Schroeder, 1974)",
"Hearts and Minds (Peter Davis, 1974)",
"Ali: Fear Eats the Soul (Rainer Werner Fassbinder, 1974)",
"A Woman Under the Influence (John Cassavetes, 1974)",
"The Phantom of Liberty (Luis Buñuel, 1974)",
"Lacombe, Lucien (Louis Malle, 1974)",
"Sweet Movie (Dušan Makavejev, 1974)",
"Arabian Nights (Pier Paolo Pasolini, 1974)",
"Parade (Jacques Tati, 1974)",
"Lady Snowblood: Love Song of Vengeance (Toshiya Fujita, 1974)",
"A Poem Is a Naked Person (Les Blank, 1974)",
"Wim Wenders: The Road Trilogy (Wim Wenders, 1974–1976)",
"Alice in the Cities (Wim Wenders, 1974)",
"Female Trouble (John Waters, 1974)",
"Claudine (John Berry, 1974)",
"The Parallax View (Alan J. Pakula, 1974)",
"Céline and Julie Go Boating (Jacques Rivette, 1974)",
"Flesh for Frankenstein (Paul Morrissey, 1973)",
"The Harder They Come (Perry Henzell, 1973)",
"Sisters (Brian De Palma, 1973)",
"Maîtresse (Barbet Schroeder, 1973)",
"Scenes from a Marriage (Ingmar Bergman, 1973)",
"The Spirit of the Beehive (Víctor Erice, 1973)",
"The Friends of Eddie Coyle (Peter Yates, 1973)",
"World On a Wire (Rainer Werner Fassbinder, 1973)",
"Badlands (Terrence Malick, 1973)",
"Touki Bouki (Djibril Diop Mambéty, 1973)",
"A River Called Titas (Ritwik Ghatak, 1973)",
"Don't Look Now (Nicolas Roeg, 1973)",
"Day for Night (François Truffaut, 1973)",
"Lady Snowblood (Toshiya Fujita, 1973)",
"Fantastic Planet (René Laloux, 1973)",
"Cries and Whispers (Ingmar Bergman, 1972)",
"The Discreet Charm of the Bourgeoisie (Luis Buñuel, 1972)",
"The Ruling Class (Peter Medak, 1972)",
"Solaris (Andrei Tarkovsky, 1972)",
"Tout va bien (Jean-Luc Godard, Jean-Pierre Gorin, 1972)",
"Murmur of the Heart (Louis Malle, 1972)",
"Love in the Afternoon (Éric Rohmer, 1972)",
"The King of Marvin Gardens (Bob Rafelson, 1972)",
"The Canterbury Tales (Pier Paolo Pasolini, 1972)",
"The Bitter Tears of Petra von Kant (Rainer Werner Fassbinder, 1972)",
"State of Siege (Costa Gavras, 1972)",
"The New Land (Jan Troell, 1972)",
"Lone Wolf and Cub (Kenji Misumi, Buichi Saito, Yoshiyuki Kuroda, 1972–1974)",
"Roma (Federico Fellini, 1972)",
"Eight Hours Don't Make a Day (Rainer Werner Fassbinder, 1972)",
"Downpour (Bahram Bayzai, 1972)",
"Walkabout (Nicolas Roeg, 1971)",
"Straw Dogs (Sam Peckinpah, 1971)",
"W.R.: Mysteries of the Organism (Dušan Makavejev, 1971)",
"Two-Lane Blacktop (Monte Hellman, 1971)",
"Mon oncle Antoine (Claude Jutra, 1971)",
"Trafic (Jacques Tati, 1971)",
"Drive, He Said (Jack Nicholson, 1971)",
"A Safe Place (Henry Jaglom, 1971)",
"The Last Picture Show (Peter Bogdanovich, 1971)",
"Harold and Maude (Hal Ashby, 1971)",
"Sunday Bloody Sunday (John Schlesinger, 1971)",
"Trilogy of Life (Pier Paolo Pasolini, 1971–1974)",
"The Decameron (Pier Paolo Pasolini, 1971)",
"Macbeth (Roman Polanski, 1971)",
"The Merchant of Four Seasons (Rainer Werner Fassbinder, 1971)",
"The Emigrants (Jan Troell, 1971)",
"A Touch of Zen (King Hu, 1971)",
"McCabe & Mrs. Miller (Robert Altman, 1971)",
"Death in Venice (Luchino Visconti, 1971)",
"Klute (Alan J. Pakula, 1971)",
"Bruce Lee: His Greatest Hits[29] (Lo Wei, Bruce Lee, Robert Clouse, 1971–1978)",
"Gimme Shelter (Albert Maysles, David Maysles, Charlotte Zwerin, 1970)",
"Bed and Board (François Truffaut, 1970)",
"The Honeymoon Killers (Leonard Kastle, 1970)",
"Le cercle rouge (Jean-Pierre Melville, 1970)",
"Equinox (Jack Woods, 1970)",
"Claire's Knee (Éric Rohmer, 1970)",
"Dodes'ka-den (Akira Kurosawa, 1970)",
"Five Easy Pieces (Bob Rafelson, 1970)",
"Investigation of a Citizen Above Suspicion (Elio Petri, 1970)",
"Donkey Skin (Jacques Demy, 1970)",
"The Confession (Costa Gavras, 1970)",
"Valerie and Her Week of Wonders (Jaromil Jireš, 1970)",
"Beyond the Valley of the Dolls (Russ Meyer, 1970)",
"Multiple Maniacs (John Waters, 1970)",
"Baal (Volker Schlöndorff, 1970)",
"Wanda (Barbara Loden, 1970)",
"Husbands (John Cassavetes, 1970)",
"Soleil Ô (Med Hondo, 1970)",
"Double Suicide (Masahiro Shinoda, 1969)",
"My Night at Maud's (Éric Rohmer, 1969)",
"Army of Shadows (Jean-Pierre Melville, 1969)",
"The Milky Way (Luis Buñuel, 1969)",
"Z (Costa Gavras, 1969)",
"Downhill Racer (Michael Ritchie, 1969)",
"Dillinger Is Dead (Marco Ferreri, 1969)",
"Easy Rider (Dennis Hopper, 1969)",
"Kes[10] (Ken Loach, 1969)",
"Medium Cool (Haskell Wexler, 1969)",
"Fellini Satyricon (Federico Fellini, 1969)",
"Women in Love (Ken Russell, 1969)",
"The Color of Pomegranates (Sergei Parajanov, 1969)",
"Midnight Cowboy (John Schlesinger, 1969)",
"The Cremator (Juraj Herz, 1969)",
"Salesman (David Maysles, Albert Maysles, Charlotte Zwerin, 1968)",
"Stolen Kisses (François Truffaut, 1968)",
"Faces (John Cassavetes, 1968)",
"Kill! (Kihachi Okamoto, 1968)",
"Symbiopsychotaxiplasm: Two Takes (William Greaves, 1968)",
"If.... (Lindsay Anderson, 1968)",
"L'enfance nue (Maurice Pialat, 1968)",
"Head (Bob Rafelson, 1968)",
"Kuroneko (Kaneto Shindo, 1968)",
"Rosemary's Baby (Roman Polanski, 1968)",
"Always for Pleasure (Les Blank, 1968–1995)",
"Death by Hanging (Nagisa Oshima, 1968)",
"The Immortal Story (Orson Welles, 1968)",
"Night of the Living Dead (George A. Romero, 1968)",
"Memories of Underdevelopment (Tomás Gutiérrez Alea, 1968)",
"Shame (Ingmar Bergman, 1968)",
"Teorema (Pier Paolo Pasolini, 1968)",
"Lucía (Humberto Solás, 1968)",
"Mandabi (Ousmane Sembène, 1968)",
"Branded to Kill (Seijun Suzuki, 1967)",
"Playtime (Jacques Tati, 1967)",
"The Firemen's Ball (Miloš Forman, 1967)",
"The Complete Monterey Pop Festival (D. A. Pennebaker, 1967 & 1986)",
"Monterey Pop (D. A. Pennebaker, 1967)",
"I Am Curious... Box Set (Vilgot Sjöman, 1967)",
"I Am Curious (Yellow) (Vilgot Sjöman, 1967)",
"I Am Curious (Blue) (Vilgot Sjöman, 1967)",
"Le Samouraï (Jean-Pierre Melville, 1967)",
"Samurai Rebellion (Masaki Kobayashi, 1967)",
"La collectionneuse (Éric Rohmer, 1967)",
"Mouchette (Robert Bresson, 1967)",
"The Two of Us (Claude Berri, 1967)",
"2 or 3 Things I Know About Her (Jean-Luc Godard, 1967)",
"Belle de jour (Luis Buñuel, 1967)",
"Weekend (Jean-Luc Godard, 1967)",
"Marketa Lazarová (František Vláčil, 1967)",
"The Young Girls of Rochefort (Jacques Demy, 1967)",
"In Cold Blood (Richard Brooks, 1967)",
"Dont Look Back (D. A. Pennebaker, 1967)",
"The Graduate (Mike Nichols, 1967)",
"Valley of the Dolls (Mark Robson, 1967)",
"Festival (Murray Lerner, 1967)",
"Dragon Inn (King Hu, 1967)",
"In the Heat of the Night (Norman Jewison, 1967)",
"Andrei Rublev (Andrei Tarkovsky, 1966)",
"Tokyo Drifter (Seijun Suzuki, 1966)",
"Closely Watched Trains (Jiří Menzel, 1966)",
"The Pornographers (Shohei Imamura, 1966)",
"The Battle of Algiers (Gillo Pontecorvo, 1966)",
"Fighting Elegy (Seijun Suzuki, 1966)",
"Young Törless (Volker Schlöndorff, 1966)",
"The Sword of Doom (Kihachi Okamoto, 1966)",
"Au Hasard Balthazar (Robert Bresson, 1966)",
"Masculin féminin (Jean-Luc Godard, 1966)",
"The Face of Another (Hiroshi Teshigahara, 1966)",
"Patriotism (Domoto Masaki, Yukio Mishima, 1966)",
"Le deuxième souffle (Jean-Pierre Melville, 1966)",
"The Taking of Power by Louis XIV (Roberto Rossellini, 1966)",
"Made in U.S.A (Jean-Luc Godard, 1966)",
"Cul-de-sac (Roman Polanski, 1966)",
"A Hollis Frampton Odyssey (Hollis Frampton, 1966–1970)",
"Seconds (John Frankenheimer, 1966)",
"Persona (Ingmar Bergman, 1966)",
"The Shooting (Monte Hellman, 1966)",
"Ride in the Whirlwind (Monte Hellman, 1966)",
"Here Is Your Life (Jan Troell, 1966)",
"Chimes at Midnight (Orson Welles, 1966)",
"Black Girl (Ousmane Sembène, 1966)",
"Blow-Up (Michelangelo Antonioni, 1966)",
"Law of the Border (Lüfti Ö. Akad, 1966)",
"The Hero (Satyajit Ray, 1966)",
"War and Peace (Sergei Bondarchuk, 1966–1967)",
"Alphaville (Jean-Luc Godard, 1965)",
"Kwaidan (Masaki Kobayashi, 1965)",
"The Shop on Main Street (Elmar Klos, Ján Kadár, 1965)",
"Loves of a Blonde (Miloš Forman, 1965)",
"Juliet of the Spirits (Federico Fellini, 1965)",
"Tokyo Olympiad (Kon Ichikawa, 1965)",
"Red Beard (Akira Kurosawa, 1965)",
"Story of a Prostitute (Seijun Suzuki, 1965)",
"Sword of the Beast (Hideo Gosha, 1965)",
"Samurai Spy (Masahiro Shinoda, 1965)",
"The Naked Prey (Cornel Wilde, 1965)",
"Le bonheur (Agnès Varda, 1965)",
"Pierrot le fou (Jean-Luc Godard, 1965)",
"The Spy Who Came in from the Cold (Martin Ritt, 1965)",
"Simon of the Desert (Luis Buñuel, 1965)",
"Repulsion (Roman Polanski, 1965)",
"The Moment of Truth (Francesco Rosi, 1965)",
"I Knew Her Well (Antonio Pietrangeli, 1965)",
"The Naked Kiss (Samuel Fuller, 1964)",
"Diary of a Chambermaid (Luis Buñuel, 1964)",
"Gertrud (Carl Theodor Dreyer, 1964)",
"Band of Outsiders (Jean-Luc Godard, 1964)",
"Onibaba (Kaneto Shindo, 1964)",
"Gate of Flesh (Seijun Suzuki, 1964)",
"Seduced and Abandoned (Pietro Germi, 1964)",
"The Woman in the Dunes (Hiroshi Teshigahara, 1964)",
"Robinson Crusoe on Mars (Byron Haskin, 1964)",
"Intentions of Murder (Shohei Imamura, 1964)",
"Red Desert (Michelangelo Antonioni, 1964)",
"Pale Flower (Masahiro Shinoda, 1964)",
"Three Outlaw Samurai (Hideo Gosha, 1964)",
"Charulata (Satyajit Ray, 1964)",
"Dry Summer (Metin Erksan, 1964)",
"A Hard Day's Night (Richard Lester, 1964)",
"The Umbrellas of Cherbourg (Jacques Demy, 1964)",
"The Soft Skin (François Truffaut, 1964)",
"Dr. Strangelove, or: How I Learned, to Stop Worrying and Love the Bomb (Stanley Kubrick, 1964)",
"Diamonds of the Night (Jan Němec, 1964)",
"Fail Safe (Sidney Lumet, 1964)",
"Shock Corridor (Samuel Fuller, 1963)",
"High and Low (Akira Kurosawa, 1963)",
"Lord of the Flies (Peter Brook, 1963)",
"Charade (Stanley Donen, 1963)",
"Billy Liar (John Schlesinger, 1963)",
"8½ (Federico Fellini, 1963)",
"Contempt (Jean-Luc Godard, 1963)",
"The Silence (Ingmar Bergman, 1963)",
"The Leopard (Luchino Visconti, 1963)",
"Youth of the Beast (Seijun Suzuki, 1963)",
"Six Moral Tales (Éric Rohmer, 1963–1972)",
"The Bakery Girl of Monceau (Éric Rohmer, 1963)",
"Suzanne's Career (Éric Rohmer, 1963)",
"Hands Over the City[3] (Francesco Rosi, 1963)",
"This Sporting Life (Lindsay Anderson, 1963)",
"The Fire Within (Louis Malle, 1963)",
"The Insect Woman (Shohei Imamura, 1963)",
"The Organizer (Mario Monicelli, 1963)",
"The Big City[19] (Satyajit Ray, 1963)",
"It's a Mad, Mad, Mad, Mad World (Stanley Kramer, 1963)",
"Judex (Georges Franju, 1963)",
"Bay of Angels (Jacques Demy, 1963)",
"Muriel, or The Time of Return (Alain Resnais, 1963)",
"The Executioner (Luis García Berlanga, 1963)",
"Tom Jones (Tony Richardson, 1963)",
"An Actor's Revenge (Kon Ichikawa, 1963)",
"Le petit soldat (Jean-Luc Godard, 1963)",
"The Great Escape (John Sturges, 1963)",
"Scorsese Shorts (Martin Scorsese, 1963–1978)",
"Sanjuro (Akira Kurosawa, 1962)",
"Carnival of Souls (Herk Harvey, 1962)",
"Cléo from 5 to 7 (Agnès Varda, 1962)",
"I fidanzati (Ermanno Olmi, 1962)",
"Winter Light (Ingmar Bergman, 1962)",
"Ingmar Bergman Makes a Movie (Vilgot Sjöman, 1962)",
"Knife in the Water (Roman Polanski, 1962)",
"Mamma Roma (Pier Paolo Pasolini, 1962)",
"La commare secca (Bernardo Bertolucci, 1962)",
"L'eclisse (Michelangelo Antonioni, 1962)",
"Jules and Jim (François Truffaut, 1962)",
"Harakiri (Masaki Kobayashi, 1962)",
"La Jetée / Sans Soleil (Chris Marker, 1962 & 1983)",
"Three Films by Hiroshi Teshigahara (Hiroshi Teshigahara, 1962–1966)",
"Pitfall (Hiroshi Teshigahara, 1962)",
"Ivan's Childhood (Andrei Tarkovsky, 1962)",
"Mafioso (Alberto Lattuada, 1962)",
"An Autumn Afternoon (Yasujirō Ozu, 1962)",
"Le doulos (Jean-Pierre Melville, 1962)",
"The Exterminating Angel (Luis Buñuel, 1962)",
"Pigs, Pimps & Prostitutes:, 3 Films by Shohei Imamura (Shohei Imamura, 1962–1964)",
"Pigs and Battleships (Shohei Imamura, 1962)",
"Vivre sa vie (Jean-Luc Godard, 1962)",
"Pierre Étaix (Pierre Étaix, 1962–1971)",
"Zatoichi: The Blind Swordsman (Kenji Misumi, Kazuo Mori, Tokuzô Tanaka, Kimiyoshi Yasuda, Kazuo Ikehiro, Akira Inoue, Satsuo Yamamoto, Shintaro Katsu, 1962–1973)",
"Il sorpasso (Dino Risi, 1962)",
"Sundays and Cybele (Serge Bourguignon, 1962)",
"The Manchurian Candidate (John Frankenheimer, 1962)",
"The Fabulous Baron Munchausen (Karel Zeman, 1962)",
"Yojimbo (Akira Kurosawa, 1961)",
"Il posto (Ermanno Olmi, 1961)",
"A Film Trilogy by Ingmar Bergman (Ingmar Bergman, 1961–1963)",
"Through a Glass Darkly (Ingmar Bergman, 1961)",
"Salvatore Giuliano (Francesco Rosi, 1961)",
"A Woman Is a Woman (Jean-Luc Godard, 1961)",
"Divorce Italian Style (Pietro Germi, 1961)",
"Viridiana (Luis Buñuel, 1961)",
"Fists in the Pocket (Marco Bellocchio, 1961)",
"Blast of Silence (Allen Baron, 1961)",
"Last Year at Marienbad (Alain Resnais, 1961)",
"Léon Morin, Priest (Jean-Pierre Melville, 1961)",
"Chronicle of a Summer (Jean Rouch, Edgar Morin, 1961)",
"La notte (Michelangelo Antonioni, 1961)",
"The Essential Jacques Demy (Jacques Demy, 1961–1982)",
"Lola (Jacques Demy, 1961)",
"The Innocents (Jack Clayton, 1961)",
"Paris Belongs to Us (Jacques Rivette, 1961)",
"A Taste of Honey (Tony Richardson, 1961)",
"One-Eyed Jacks (Marlon Brando, 1961)",
"Something Wild (Jack Garfein, 1961)",
"A Raisin in the Sun (Daniel Petrie, 1961)",
"Peeping Tom (Michael Powell, 1960)",
"L'avventura (Michelangelo Antonioni, 1960)",
"Spartacus (Stanley Kubrick, 1960)",
"Le trou (Jacques Becker, 1960)",
"Tunes of Glory (Ronald Neame, 1960)",
"Eyes Without a Face (Georges Franju, 1960)",
"Shoot the Piano Player (François Truffaut, 1960)",
"The Bad Sleep Well (Akira Kurosawa, 1960)",
"The Virgin Spring (Ingmar Bergman, 1960)",
"Jigoku (Nobuo Nakagawa, 1960)",
"When a Woman Ascends the Stairs (Mikio Naruse, 1960)",
"Breathless (Jean-Luc Godard, 1960)",
"Classe tous risques (Claude Sautet, 1960)",
"The Fugitive Kind (Sidney Lumet, 1960)",
"Zazie dans le Métro (Louis Malle, 1960)",
"Purple Noon (René Clément, 1960)",
"The Housemaid (Kim Ki-young, 1960)",
"La dolce vita (Federico Fellini, 1960)",
"The Kennedy Films of Robert Drew & Associates (Robert Drew, 1960–1964)",
"The Naked Island (Kaneto Shindo, 1960)",
"La vérité (Henri-Georges Clouzot, 1960)",
"The Cloud-Capped Star (Ritwik Ghatak, 1960)",
"The 400 Blows (François Truffaut, 1959)",
"Black Orpheus (Marcel Camus, 1959)",
"Testament of Orpheus (Jean Cocteau, 1959)",
"Good Morning[25] (Yasujirō Ozu, 1959)",
"Ballad of a Soldier (Grigori Chukhrai, 1959)",
"The Adventures of Antoine Doinel (François Truffaut, 1959–1979)",
"Hiroshima mon amour (Alain Resnais, 1959)",
"John Cassavetes: Five Films (John Cassavetes, Charles Kiselyak, 1959–2000)",
"Shadows (John Cassavetes, 1959)",
"Pickpocket (Robert Bresson, 1959)",
"First Man into Space (Robert Day, 1959)",
"The Atomic Submarine (Spencer Gordon Bennet, 1959)",
"Corridors of Blood (Robert Day, 1959)",
"Fires on the Plain (Kon Ichikawa, 1959)",
"Il Generale Della Rovere (Roberto Rossellini, 1959)",
"The Human Condition (Masaki Kobayashi, 1959)",
"Les cousins (Claude Chabrol, 1959)",
"Anatomy of a Murder (Otto Preminger, 1959)",
"Letter Never Sent (Mikhail Kalatozov, 1959)",
"The Bridge (Bernhard Wicki, 1959)",
"Apur Sansar (Satyajit Ray, 1959)",
"Some Like It Hot (Billy Wilder, 1959)",
"A Night to Remember (Roy Ward Baker, 1958)",
"The Blob (Irvin S. Yeaworth, 1958)",
"Fiend Without a Face (Arthur Crabtree, 1958)",
"Mon oncle (Jacques Tati, 1958)",
"Big Deal on Madonna Street (Mario Monicelli, 1958)",
"The Hidden Fortress (Akira Kurosawa, 1958)",
"The Horse's Mouth (Ronald Neame, 1958)",
"Ashes and Diamonds (Andrzej Wajda, 1958)",
"Monsters and Madmen (Spencer Gordon Bennet, Robert Day, 1958–1959)",
"The Haunted Strangler (Robert Day, 1958)",
"The Lovers (Louis Malle, 1958)",
"The Magician (Ingmar Bergman, 1958)",
"The Music Room (Satyajit Ray, 1958)",
"Le beau Serge (Claude Chabrol, 1958)",
"The Ballad of Narayama (Keisuke Kinoshita, 1958)",
"Invention for Destruction (Karel Zeman, 1958)",
"The Seventh Seal (Ingmar Bergman, 1957)",
"Nights of Cabiria (Federico Fellini, 1957)",
"Wild Strawberries (Ingmar Bergman, 1957)",
"The Cranes Are Flying (Mikhail Kalatozov, 1957)",
"Throne of Blood (Akira Kurosawa, 1957)",
"Kanał (Andrzej Wajda, 1957)",
"Le notti bianche (Luchino Visconti, 1957)",
"Elevator to the Gallows (Louis Malle, 1957)",
"Martha Graham: Dance on Film (Nathan Kroll, 1957–1961)",
"Paths of Glory (Stanley Kubrick, 1957)",
"Sweet Smell of Success (Alexander Mackendrick, 1957)",
"12 Angry Men[13] (Sidney Lumet, 1957)",
"3:10 to Yuma (Delmer Daves, 1957)",
"Forty Guns (Samuel Fuller, 1957)",
"A Face in the Crowd (Elia Kazan, 1957)",
"Samurai III: Duel at Ganryu Island (Hiroshi Inagaki, 1956)",
"And God Created Woman (Roger Vadim, 1956)",
"Written on the Wind (Douglas Sirk, 1956)",
"Bob le flambeur (Jean-Pierre Melville, 1956)",
"Elena and Her Men (Jean Renoir, 1956)",
"Crazed Fruit (Kō Nakahira, 1956)",
"The Burmese Harp (Kon Ichikawa, 1956)",
"4 by Agnès Varda (Agnès Varda, 1956–1985)",
"La Pointe Courte (Agnès Varda, 1956)",
"Bigger Than Life (Nicholas Ray, 1956)",
"The Killing[12] (Stanley Kubrick, 1956)",
"A Man Escaped (Robert Bresson, 1956)",
"Jubal (Delmer Daves, 1956)",
"Aparajito (Satyajit Ray, 1956)",
"Samurai II: Duel at Ichijoji Temple (Hiroshi Inagaki, 1955)",
"Summertime (David Lean, 1955)",
"All That Heaven Allows (Douglas Sirk, 1955)",
"Rififi (Jules Dassin, 1955)",
"Ordet (Carl Theodor Dreyer, 1955)",
"Night and Fog (Alain Resnais, 1955)",
"Richard III (Laurence Olivier, 1955)",
"Smiles of a Summer Night (Ingmar Bergman, 1955)",
"French Cancan (Jean Renoir, 1955)",
"Andrzej Wajda: Three War Films (Andrzej Wajda, 1955–1958)",
"A Generation (Andrzej Wajda, 1955)",
"The Complete Mr. Arkadin (Orson Welles, 1955)",
"Death of a Cyclist (Juan Antonio Bardem, 1955)",
"Lola Montès (Max Ophüls, 1955)",
"The Night of the Hunter (Charles Laughton, 1955)",
"Kiss Me Deadly (Robert Aldrich, 1955)",
"The Apu Trilogy (Satyajit Ray, 1955–1959)",
"Pather Panchali (Satyajit Ray, 1955)",
"Le amiche (Michelangelo Antonioni, 1955)",
"Journey to the Beginning of Time (Karel Zeman, 1955)",
"Seven Samurai (Akira Kurosawa, 1954)",
"Samurai I: Musashi Miyamoto (Hiroshi Inagaki, 1954)",
"Diabolique (Henri-Georges Clouzot, 1954)",
"by Brakhage: an Anthology (Stan Brakhage, 1954–2001)",
"La strada (Federico Fellini, 1954)",
"Touchez pas au grisbi (Jacques Becker, 1954)",
"Sansho the Bailiff (Kenji Mizoguchi, 1954)",
"Twenty-Four Eyes (Keisuke Kinoshita, 1954)",
"Magnificent Obsession[7] (Douglas Sirk, 1954)",
"Hobson's Choice (David Lean, 1954)",
"Senso (Luchino Visconti, 1954)",
"Godzilla[14] (Ishirō Honda, 1954)",
"On the Waterfront (Elia Kazan, 1954)",
"Journey to Italy (Roberto Rossellini, 1954)",
"Riot in Cell Block 11 (Don Siegel, 1954)",
"A Story from Chikamatsu (Kenji Mizoguchi, 1954)",
"Godzilla: The Shōwa-Era Films, 1954–1975 (Ishirō Honda, Jun Fukuda, Motoyoshi Oda, Yoshimitsu Banno, 1954–1975)",
"After the Curfew (Usmar Ismail, 1954)",
"The Wages of Fear (Henri-Georges Clouzot, 1953)",
"Monsieur Hulot's Holiday (Jacques Tati, 1953)",
"Indiscretion of an American Wife (Vittorio De Sica, 1953)",
"Tokyo Story (Yasujirō Ozu, 1953)",
"Pickup on South Street (Samuel Fuller, 1953)",
"Stage and Spectacle:, Three Films by Jean Renoir (Jean Renoir, 1953–1956)",
"The Golden Coach (Jean Renoir, 1953)",
"I vitelloni (Federico Fellini, 1953)",
"Ugetsu (Kenji Mizoguchi, 1953)",
"Sawdust and Tinsel (Ingmar Bergman, 1953)",
"The Earrings of Madame de... (Max Ophüls, 1953)",
"The Golden Age of Television (Delbert Mann, Fielder Cook, Alex Segal, Daniel Petrie, Cordelia Stone, Ralph Nelson, John Frankenheimer, 1953–1958)",
"By Brakhage: An Anthology, Volume Two (Stan Brakhage, 1953–2003)",
"By Brakhage: An Anthology, Volumes One and Two (Stan Brakhage, 1953–2003)",
"Summer with Monika (Ingmar Bergman, 1953)",
"Gate of Hell (Teinosuke Kinugasa, 1953)",
"The War of the Worlds (Byron Haskin, 1953)",
"The Importance of Being Earnest (Anthony Asquith, 1952)",
"The White Sheik (Federico Fellini, 1952)",
"Umberto D. (Vittorio De Sica, 1952)",
"Ikiru (Akira Kurosawa, 1952)",
"Casque d'or (Jacques Becker, 1952)",
"Le plaisir (Max Ophüls, 1952)",
"Fanfan la Tulipe (Christian Jaque, 1952)",
"The Life of Oharu (Kenji Mizoguchi, 1952)",
"Europa '51 (Roberto Rossellini, 1952)",
"Limelight (Charlie Chaplin, 1952)",
"Othello (Orson Welles, 1952)",
"The Flavor of Green Tea over Rice (Yasujirō Ozu, 1952)",
"Diary of a Country Priest (Robert Bresson, 1951)",
"Early Summer (Yasujirō Ozu, 1951)",
"The River (Jean Renoir, 1951)",
"The Browning Version (Anthony Asquith, 1951)",
"The Tales of Hoffmann (Michael Powell, Emeric Pressburger, 1951)",
"Forbidden Games (René Clément, 1951)",
"Ace in the Hole (Billy Wilder, 1951)",
"Miss Julie (Alf Sjöberg, 1951)",
"Summer Interlude (Ingmar Bergman, 1951)",
"La poison (Sacha Guitry, 1951)",
"Variety Lights (Federico Fellini, Alberto Lattuada, 1950)",
"Rashomon (Akira Kurosawa, 1950)",
"Night and the City (Jules Dassin, 1950)",
"The Flowers of St. Francis (Roberto Rossellini, 1950)",
"Les enfants terribles (Jean-Pierre Melville, 1950)",
"The Furies (Anthony Mann, 1950)",
"La ronde (Max Ophüls, 1950)",
"3 Films by Roberto Rossellini, Starring Ingrid Bergman (Roberto Rossellini, 1950–1954)",
"Stromboli (Roberto Rossellini, 1950)",
"In a Lonely Place (Nicholas Ray, 1950)",
"The Asphalt Jungle (John Huston, 1950)",
"The Breaking Point (Michael Curtiz, 1950)",
"All About Eve (Joseph L. Mankiewicz, 1950)",
"The Gunfighter (Henry King, 1950)",
"The Third Man (Carol Reed, 1949)",
"Orpheus (Jean Cocteau, 1949)",
"Stray Dog (Akira Kurosawa, 1949)",
"Thieves' Highway (Jules Dassin, 1949)",
"Kind Hearts and Coronets (Robert Hamer, 1949)",
"Late Spring (Yasujirō Ozu, 1949)",
"The Small Back Room (Michael Powell, Emeric Pressburger, 1949)",
"The Complete Jacques Tati (Jacques Tati, 1949–1974)",
"Jour de fête (Jacques Tati, 1949)",
"Le silence de la mer (Jean-Pierre Melville, 1949)",
"Bitter Rice (Giuseppe De Santis, 1949)",
"The Heiress (William Wyler, 1949)",
"Oliver Twist (David Lean, 1948)",
"The Red Shoes (Michael Powell, Emeric Pressburger, 1948)",
"Hamlet (Laurence Olivier, 1948)",
"Unfaithfully Yours (Preston Sturges, 1948)",
"The Fallen Idol (Carol Reed, 1948)",
"Bicycle Thieves (Vittorio De Sica, 1948)",
"The Naked City (Jules Dassin, 1948)",
"Drunken Angel (Akira Kurosawa, 1948)",
"Germany, Year Zero (Roberto Rossellini, 1948)",
"Red River (Howard Hawks, 1948)",
"They Live by Night (Nicholas Ray, 1948)",
"Moonrise (Frank Borzage, 1948)",
"Black Narcissus (Michael Powell, Emeric Pressburger, 1947)",
"Quai des Orfèvres (Henri-Georges Clouzot, 1947)",
"Brute Force (Jules Dassin, 1947)",
"Monsieur Verdoux (Charlie Chaplin, 1947)",
"Ride the Pink Horse (Robert Montgomery, 1947)",
"Odd Man Out (Carol Reed, 1947)",
"Panique (Julien Duvivier, 1947)",
"Beauty and the Beast (Jean Cocteau, 1946)",
"Great Expectations (David Lean, 1946)",
"Notorious (Alfred Hitchcock, 1946)",
"The Killers (3 adaptations) (Robert Siodmak, Andrei Tarkovsky, Don Siegel, 1946–1964)",
"Green for Danger (Sidney Gilliat, 1946)",
"Paisan (Roberto Rossellini, 1946)",
"My Darling Clementine (John Ford, 1946)",
"Gilda (Charles Vidor, 1946)",
"A Matter of Life and Death (Michael Powell, Emeric Pressburger, 1946)",
"Cluny Brown (Ernst Lubitsch, 1946)",
"Brief Encounter (David Lean, 1945)",
"I Know Where I'm Going! (Michael Powell, Emeric Pressburger, 1945)",
"Spellbound (Alfred Hitchcock, 1945)",
"Children of Paradise (Marcel Carné, 1945)",
"Les dames du Bois de Boulogne (Robert Bresson, 1945)",
"Rome, Open City (Roberto Rossellini, 1945)",
"Roberto Rossellini's War Trilogy (Roberto Rossellini, 1945–1948)",
"Blithe Spirit (David Lean, 1945)",
"Mildred Pierce (Michael Curtiz, 1945)",
"Detour (Edgar G. Ulmer, 1945)",
"Leave Her to Heaven (John M. Stahl, 1945)",
"Henry V (Laurence Olivier, 1944)",
"Ivan the Terrible (Sergei Eisenstein, 1944 & 1958)",
"The Children Are Watching Us (Vittorio De Sica, 1944)",
"A Canterbury Tale (Michael Powell, Emeric Pressburger, 1944)",
"This Happy Breed (David Lean, 1944)",
"Ministry of Fear (Fritz Lang, 1944)",
"The Uninvited (Lewis Allen, 1944)",
"Carl Theodor Dreyer Box Set (Carl Theodor Dreyer, Torben Skjodt Jensen, 1943–1995)",
"Day of Wrath (Carl Theodor Dreyer, 1943)",
"The Life and Death of Colonel Blimp (Michael Powell, Emeric Pressburger, 1943)",
"Le Corbeau (Henri-Georges Clouzot, 1943)",
"Heaven Can Wait (Ernst Lubitsch, 1943)",
"Sullivan's Travels (Preston Sturges, 1942)",
"There Was a Father (Yasujirō Ozu, 1942)",
"David Lean Directs Noël Coward (David Lean, Noël Coward, 1942–1945)",
"In Which We Serve (David Lean, Noël Coward, 1942)",
"Les visiteurs du soir (Marcel Carné, 1942)",
"To Be or Not to Be (Ernst Lubitsch, 1942)",
"I Married a Witch (René Clair, 1942)",
"The Palm Beach Story (Preston Sturges, 1942)",
"Cat People (Jacques Tourneur, 1942)",
"Woman of the Year (George Stevens, 1942)",
"The Magnificent Ambersons (Orson Welles, 1942)",
"Now, Voyager (Irving Rapper, 1942)",
"The Lady Eve (Preston Sturges, 1941)",
"The Devil and Daniel Webster (William Dieterle, 1941)",
"49th Parallel (Michael Powell, Emeric Pressburger, 1941)",
"That Hamilton Woman (Alexander Korda, 1941)",
"Here Comes Mr. Jordan (Alexander Hall, 1941)",
"The Bank Dick (Edward Cline, 1940)",
"Rebecca (Alfred Hitchcock, 1940)",
"Citizen of the World: The Proud Valley / Native Land (Pen Tennyson, Leo Hurwitz, Paul Strand, 1940 & 1942)",
"The Thief of Bagdad[6] (Ludwig Berger, Michael Powell, Tim Whelan, 1940)",
"Night Train to Munich (Carol Reed, 1940)",
"The Great Dictator (Charlie Chaplin, 1940)",
"Foreign Correspondent (Alfred Hitchcock, 1940)",
"His Girl Friday[24] (Howard Hawks, 1940)",
"The Philadelphia Story (George Cukor, 1940)",
"Dance, Girl, Dance (Dorothy Arzner, 1940)",
"The Rules of the Game (Jean Renoir, 1939)",
"Young Mr. Lincoln (John Ford, 1939)",
"Stagecoach[8] (John Ford, 1939)",
"The Mikado (Victor Schertzinger, 1939)",
"The Four Feathers (Zoltan Korda, 1939)",
"Only Angels Have Wings (Howard Hawks, 1939)",
"The Story of the Last Chrysanthemum (Kenji Mizoguchi, 1939)",
"Destry Rides Again (George Marshall, 1939)",
"The Lady Vanishes[1] (Alfred Hitchcock, 1938)",
"Pygmalion (Anthony Asquith, Leslie Howard, 1938)",
"Eisenstein: The Sound Years (Sergei Eisenstein, 1938–1958)",
"Alexander Nevsky (Sergei Eisenstein, 1938)",
"Port of Shadows (Marcel Carné, 1938)",
"La bête humaine (Jean Renoir, 1938)",
"The Baker's Wife (Marcel Pagnol, 1938)",
"Holiday (George Cukor, 1938)",
"Grand Illusion (Jean Renoir, 1937)",
"Make Way for Tomorrow (Leo McCarey, 1937)",
"The Awful Truth (Leo McCarey, 1937)",
"My Man Godfrey (Gregory La Cava, 1936)",
"Pépé le moko (Julien Duvivier, 1936)",
"The Lower Depths (1936 film 1957 film) (Jean Renoir, Akira Kurosawa, 1936 & 1957)",
"Two Films by Yasujiro Ozu (Yasujirō Ozu, 1936 & 1942)",
"The Only Son (Yasujirō Ozu, 1936)",
"Modern Times (Charlie Chaplin, 1936)",
"Things to Come (William Cameron Menzies, 1936)",
"Martin Scorsese's, World Cinema Project (, 1936–1981)",
"Redes (Emilio Gómez Muriel,, Fred Zinnemann, 1936)",
"A Day in the Country (Jean Renoir, 1936)",
"César (Marcel Pagnol, 1936)",
"Swing Time (George Stevens, 1936)",
"Show Boat (James Whale, 1936)",
"The 39 Steps (Alfred Hitchcock, 1935)",
"Pioneer: Sanders of the River / Jericho (Zoltan Korda, Thornton Freeland, 1935 & 1937)",
"The Devil Is a Woman (Josef von Sternberg, 1935)",
"Toni (Jean Renoir, 1935)",
"The Scarlet Empress (Josef von Sternberg, 1934)",
"A Story of Floating Weeds / Floating Weeds (Yasujirō Ozu, 1934 & 1959)",
"The Man Who Knew Too Much (Alfred Hitchcock, 1934)",
"It Happened One Night (Frank Capra, 1934)",
"Martin Scorsese's, World Cinema Project No. 3 (, 1934–1981)",
"Dos monjes (Juan Bustillo Oro, 1934)",
"The Testament of Dr. Mabuse (Fritz Lang, 1933)",
"Icon: The Emperor Jones /, Paul Robeson: Tribute to an Artist (Dudley Murphy, Saul J. Turell, 1933 & 1979)",
"Design for Living (Ernst Lubitsch, 1933)",
"The Story of Temple Drake (Stephen Roberts, 1933)",
"The Most Dangerous Game (Ernest B. Schoedsack, Irving Pichel, 1932)",
"Trouble in Paradise (Ernst Lubitsch, 1932)",
"Boudu Saved from Drowning (Jean Renoir, 1932)",
"Vampyr (Carl Theodor Dreyer, 1932)",
"Island of Lost Souls (Erle C. Kenton, 1932)",
"Fanny (Marc Allégret, 1932)",
"Shanghai Express (Josef von Sternberg, 1932)",
"Blonde Venus (Josef von Sternberg, 1932)",
"M (Fritz Lang, 1931)",
"Le million (René Clair, 1931)",
"À nous la liberté (René Clair, 1931)",
"The Threepenny Opera (Georg Wilhelm Pabst, 1931)",
"City Lights (Charlie Chaplin, 1931)",
"La chienne [23] (Jean Renoir, 1931)",
"Martin Scorsese's, World Cinema Project No. 2 (, 1931–2000)",
"Limite (Mário Peixoto, 1931)",
"The Marseille Trilogy (, 1931–1936)",
"Marius (Alexander Korda, 1931)",
"Kameradschaft (G. W. Pabst, 1931)",
"Dishonored (Josef von Sternberg, 1931)",
"The Orphic Trilogy (Jean Cocteau, 1930–1959)",
"The Blood of a Poet (Jean Cocteau, 1930)",
"Under the Roofs of Paris (René Clair, 1930)",
"People on Sunday (Robert Siodmak, Edgar G. Ulmer, 1930)",
"The Complete Jean Vigo (Jean Vigo, 1930–1934)",
"Westfront 1918 (G. W. Pabst, 1930)",
"King of Jazz (John Murray Anderson, 1930)",
"Dietrich & von Sternberg in Hollywood (Josef von Sternberg, 1930–1935)",
"Morocco (Josef von Sternberg, 1930)",
"Pandora's Box (Georg Wilhelm Pabst, 1929)",
"The Passion of Joan of Arc (Carl Theodor Dreyer, 1928)",
"The Last Command (Josef von Sternberg, 1928)",
"The Docks of New York (Josef von Sternberg, 1928)",
"Lonesome[17] [18] (Paul Fejos, 1928)",
"Speedy (Ted Wilde, 1928)",
"The Circus (Charlie Chaplin, 1928)",
"The Cameraman[28] (Edward Sedgwick, 1928)",
"The King of Kings (Cecil B. DeMille, 1927)",
"Three Silent Classics, by Josef von Sternberg (Josef von Sternberg, 1927 & 1928)",
"Underworld (Josef von Sternberg, 1927)",
"The Lodger: A Story of the London Fog[26] (Alfred Hitchcock, 1927)",
"The Kid Brother (Ted Wilde, 1927)",
"Paul Robeson: Portraits of the Artist (Dudley Murphy, Saul J. Turell, Oscar Micheaux, Kenneth Macpherson, Zoltan Korda, Thornton Freeland, Pen Tennyson, Leo Hurwitz, Paul Strand, 1925–1979)",
"Outsider: Body and Soul / Borderline (Oscar Micheaux, Kenneth Macpherson, 1925 & 1930)",
"Science Is Fiction: 23 Films by Jean Painlevé (Jean Painlevé, 1925–1986)",
"The Gold Rush (Charlie Chaplin, 1925 & 1942)",
"The Freshman (Fred Newmeyer, Sam Taylor, 1925)",
"Master of the House (Carl Theodor Dreyer, 1925)",
"Safety Last! (Fred Newmeyer, Sam Taylor, 1923)",
"Nanook of the North (Robert Flaherty, 1922)",
"Häxan: Witchcraft Through the Ages (Benjamin Christensen, 1922)",
"The Phantom Carriage (Victor Sjöström, 1921)",
"The Kid (Charlie Chaplin, 1921)",
"W. C. Fields—Six Short Films (Monte Brice, Clyde Bruckman, Edwin Middleton, Leslie Pearce, Arthur Ripley, 1915–1933)",
"100 Years of Olympic Films: 1912–2012 (, 1912–2012)"
]